/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "utils.h"
#include "detector_parameters_data.h"
#include "log.h"

#include "vehicleDetectorTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table vehicleDetectorTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::vehicleDetectorTable is subid 2 of detector.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.2, length: 12
*/

/**
 * initialization for vehicleDetectorTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param vehicleDetectorTable_reg
 *        Pointer to vehicleDetectorTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */



int
vehicleDetectorTable_init_data(vehicleDetectorTable_registration * vehicleDetectorTable_reg)
{
    DEBUGMSGTL(("verbose:vehicleDetectorTable:vehicleDetectorTable_init_data","called\n"));

    static unsigned int table_columns[] = {
        COLUMN_VEHICLEDETECTORNUMBER,
        COLUMN_VEHICLEDETECTOROPTIONS,
        COLUMN_VEHICLEDETECTORCALLPHASE,
        COLUMN_VEHICLEDETECTORSWITCHPHASE,
        COLUMN_VEHICLEDETECTORDELAY,
        COLUMN_VEHICLEDETECTOREXTEND,
        COLUMN_VEHICLEDETECTORQUEUELIMIT,
        COLUMN_VEHICLEDETECTORNOACTIVITY,
        COLUMN_VEHICLEDETECTORMAXPRESENCE,
        COLUMN_VEHICLEDETECTORERRATICCOUNTS,
        COLUMN_VEHICLEDETECTORFAILTIME,
        COLUMN_VEHICLEDETECTORALARMS,
        COLUMN_VEHICLEDETECTORREPORTEDALARMS,
        COLUMN_VEHICLEDETECTORRESET,
        COLUMN_VEHICLEDETECTOROPTIONS2,
        COLUMN_VEHICLEDETECTORPAIREDDETECTOR,
        COLUMN_VEHICLEDETECTORPAIREDDETECTORSPACING,
        COLUMN_VEHICLEDETECTORAVGVEHICLELENGTH,
        COLUMN_VEHICLEDETECTORLENGTH,
        COLUMN_VEHICLEDETECTORTRAVELMODE
    };

    static netsnmp_column_info valid_columns;
    valid_columns.isRange = 0;
    valid_columns.details.list = table_columns;
    valid_columns.list_count = sizeof(table_columns)/sizeof(unsigned int);
    vehicleDetectorTable_valid_columns_set(&valid_columns);

    return MFD_SUCCESS;
} /* vehicleDetectorTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
vehicleDetectorTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache)
{
    DEBUGMSGTL(("verbose:vehicleDetectorTable:vehicleDetectorTable_container_init","called\n"));
    
    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,"bad container param to vehicleDetectorTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,"bad cache param to vehicleDetectorTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up vehicleDetectorTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = VEHICLEDETECTORTABLE_CACHE_TIMEOUT; /* seconds */
} /* vehicleDetectorTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before vehicleDetectorTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
vehicleDetectorTable_container_shutdown(netsnmp_container *container_ptr)
{
    DEBUGMSGTL(("verbose:vehicleDetectorTable:vehicleDetectorTable_container_shutdown","called\n"));
    
    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,"bad params to vehicleDetectorTable_container_shutdown\n");
        return;
    }

} /* vehicleDetectorTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement vehicleDetectorTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data involves more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  vehicleDetectorTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
vehicleDetectorTable_container_load(netsnmp_container *container)
{
    vehicleDetectorTable_rowreq_ctx *rowreq_ctx;
    size_t                 count = 0;

    log_debug(" container load a girdi girdi   vehicleDetectorTable_data_access .c- 222.satır\n");
    /*
     * storage for each column
     */
    long   vehicleDetectorNumber;

    DEBUGMSGTL(("verbose:vehicleDetectorTable:vehicleDetectorTable_container_load","called\n"));

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    vehicleDetectorTable_rowreq_ctx *table_ptr = NULL;

    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    /*
     * TODO:351:M: |-> Load/update data in the vehicleDetectorTable container.
     * loop over your vehicleDetectorTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
    while( 1 ) {
        /*
        ***************************************************
        ***             START EXAMPLE CODE              ***
        ***---------------------------------------------***/
        table_ptr = get_vehicle_detector_table(count);

        /*
        * check for end of data
        */
        if(NULL == table_ptr)
            break;

        /*
        * parse line into variables
        */
        vehicleDetectorNumber = table_ptr->tbl_idx.vehicleDetectorNumber;
        /*
        ***---------------------------------------------***
        ***              END  EXAMPLE CODE              ***
        ***************************************************/

        /*
         * TODO:352:M: |   |-> set indexes in new vehicleDetectorTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */
        rowreq_ctx = vehicleDetectorTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if(MFD_SUCCESS != vehicleDetectorTable_indexes_set(rowreq_ctx
                               , table_ptr->tbl_idx.vehicleDetectorNumber
               )) {
            snmp_log(LOG_ERR,"error setting index while loading "
                     "vehicleDetectorTable data.\n");
                     
            vehicleDetectorTable_release_rowreq_ctx(rowreq_ctx);
            //continue;
            return MFD_RESOURCE_UNAVAILABLE;

        }

        /*
         * TODO:352:r: |   |-> populate vehicleDetectorTable data context.
         * Populate data context here. (optionally, delay until row prep)
         */
        /*
        * TRANSIENT or semi-TRANSIENT data:
        * copy data or save any info needed to do it in row_prep.
        */
        /*
        * setup/save data for vehicleDetectorOptions
        * vehicleDetectorOptions(2)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorOptions = table_ptr->data.vehicleDetectorOptions;
        
        /*
        * setup/save data for vehicleDetectorCallPhase
        * vehicleDetectorCallPhase(4)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorCallPhase = table_ptr->data.vehicleDetectorCallPhase;
        
        /*
        * setup/save data for vehicleDetectorSwitchPhase
        * vehicleDetectorSwitchPhase(5)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorSwitchPhase = table_ptr->data.vehicleDetectorSwitchPhase;
        
        /*
        * setup/save data for vehicleDetectorDelay
        * vehicleDetectorDelay(6)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorDelay = table_ptr->data.vehicleDetectorDelay;
        
        /*
        * setup/save data for vehicleDetectorExtend
        * vehicleDetectorExtend(7)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorExtend = table_ptr->data.vehicleDetectorExtend;
        
        /*
        * setup/save data for vehicleDetectorQueueLimit
        * vehicleDetectorQueueLimit(8)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorQueueLimit = table_ptr->data.vehicleDetectorQueueLimit;
        
        /*
        * setup/save data for vehicleDetectorNoActivity
        * vehicleDetectorNoActivity(9)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorNoActivity = table_ptr->data.vehicleDetectorNoActivity;
        
        /*
        * setup/save data for vehicleDetectorMaxPresence
        * vehicleDetectorMaxPresence(10)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorMaxPresence = table_ptr->data.vehicleDetectorMaxPresence;
        
        /*
        * setup/save data for vehicleDetectorErraticCounts
        * vehicleDetectorErraticCounts(11)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorErraticCounts = table_ptr->data.vehicleDetectorErraticCounts;
        
        /*
        * setup/save data for vehicleDetectorFailTime
        * vehicleDetectorFailTime(12)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorFailTime = table_ptr->data.vehicleDetectorFailTime;
        
        /*
        * setup/save data for vehicleDetectorAlarms
        * vehicleDetectorAlarms(13)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorAlarms = table_ptr->data.vehicleDetectorAlarms;
        
        /*
        * setup/save data for vehicleDetectorReportedAlarms
        * vehicleDetectorReportedAlarms(14)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorReportedAlarms = table_ptr->data.vehicleDetectorReportedAlarms;
        
        /*
        * setup/save data for vehicleDetectorReset
        * vehicleDetectorReset(15)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorReset = table_ptr->data.vehicleDetectorReset;
        
        /*
        * setup/save data for vehicleDetectorOptions2
        * vehicleDetectorOptions2(16)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorOptions2 = table_ptr->data.vehicleDetectorOptions2;
        
        /*
        * setup/save data for vehicleDetectorPairedDetector
        * vehicleDetectorPairedDetector(17)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/D/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorPairedDetector = table_ptr->data.vehicleDetectorPairedDetector;
        
        /*
        * setup/save data for vehicleDetectorPairedDetectorSpacing
        * vehicleDetectorPairedDetectorSpacing(18)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/D/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorPairedDetectorSpacing = table_ptr->data.vehicleDetectorPairedDetectorSpacing;
        
        /*
        * setup/save data for vehicleDetectorAvgVehicleLength
        * vehicleDetectorAvgVehicleLength(19)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/d/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorAvgVehicleLength = table_ptr->data.vehicleDetectorAvgVehicleLength;
        
        /*
        * setup/save data for vehicleDetectorLength
        * vehicleDetectorLength(20)/INTEGER/ASN_INTEGER/long(long)//l/A/W/e/R/D/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorLength = table_ptr->data.vehicleDetectorLength;
        
        /*
        * setup/save data for vehicleDetectorTravelMode
        * vehicleDetectorTravelMode(21)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
        */
        /** no mapping */
        rowreq_ctx->data.vehicleDetectorTravelMode = table_ptr->data.vehicleDetectorTravelMode;
    
        
        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;
    }

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/

    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    DEBUGMSGT(("verbose:vehicleDetectorTable:vehicleDetectorTable_container_load",
               "inserted %" NETSNMP_PRIz "u records\n", count));

    return MFD_SUCCESS;
} /* vehicleDetectorTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
vehicleDetectorTable_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:vehicleDetectorTable:vehicleDetectorTable_container_free","called\n"));

    /*
     * TODO:380:M: Free vehicleDetectorTable container data.
     */
} /* vehicleDetectorTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
vehicleDetectorTable_row_prep( vehicleDetectorTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:vehicleDetectorTable:vehicleDetectorTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* vehicleDetectorTable_row_prep */

/*
 * TODO:420:r: Implement vehicleDetectorTable index validation.
 */
/*---------------------------------------------------------------------
 * NTCIP1202-v03::vehicleDetectorEntry.vehicleDetectorNumber
 * vehicleDetectorNumber is subid 1 of vehicleDetectorEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.2.1.1
 * Description:
<Definition> The vehicle detector number for objects in
this row. The value shall not exceed the maxVehicleDetectors
object value.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.2.1.1
<Unit> detector
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * check validity of vehicleDetectorNumber index portion
 *
 * @retval MFD_SUCCESS   : the incoming value is legal
 * @retval MFD_ERROR     : the incoming value is NOT legal
 *
 * @note this is not the place to do any checks for the sanity
 *       of multiple indexes. Those types of checks should be done in the
 *       vehicleDetectorTable_validate_index() function.
 *
 * @note Also keep in mind that if the index refers to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 * The following checks have already been done for you:
 *    The value is in (one of) the range set(s):  1 - 255
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 */
int
vehicleDetectorNumber_check_index( vehicleDetectorTable_rowreq_ctx *rowreq_ctx )
{
    DEBUGMSGTL(("verbose:vehicleDetectorTable:vehicleDetectorNumber_check_index","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:426:M: |-> Check vehicleDetectorTable index vehicleDetectorNumber.
     * check that index value in the table context is legal.
     * (rowreq_ctx->tbl_index.vehicleDetectorNumber)
     */

    return MFD_SUCCESS; /* vehicleDetectorNumber index ok */
} /* vehicleDetectorNumber_check_index */

/**
 * verify specified index is valid.
 *
 * This check is independent of whether or not the values specified for
 * the columns of the new row are valid. Column values and row consistency
 * will be checked later. At this point, only the index values should be
 * checked.
 *
 * All of the individual index validation functions have been called, so this
 * is the place to make sure they are valid as a whole when combined. If
 * you only have one index, then you probably don't need to do anything else
 * here.
 * 
 * @note Keep in mind that if the indexes refer to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 *
 * @param vehicleDetectorTable_reg
 *        Pointer to the user registration data
 * @param vehicleDetectorTable_rowreq_ctx
 *        Pointer to the users context.
 * @retval MFD_SUCCESS            : success
 * @retval MFD_CANNOT_CREATE_NOW  : index not valid right now
 * @retval MFD_CANNOT_CREATE_EVER : index never valid
 */
int
vehicleDetectorTable_validate_index( vehicleDetectorTable_registration * vehicleDetectorTable_reg,
                           vehicleDetectorTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:vehicleDetectorTable:vehicleDetectorTable_validate_index","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:430:M: |-> Validate potential vehicleDetectorTable index.
     */
    if(1) {
        snmp_log(LOG_WARNING,"invalid index for a new row in the "
                 "vehicleDetectorTable table.\n");
        /*
         * determine failure type.
         *
         * If the index could not ever be created, return MFD_NOT_EVER
         * If the index can not be created under the present circumstances
         * (even though it could be created under other circumstances),
         * return MFD_NOT_NOW.
         */
        if(0) {
            return MFD_CANNOT_CREATE_EVER;
        }
        else {
            return MFD_CANNOT_CREATE_NOW;
        }
    }

    return rc;
} /* vehicleDetectorTable_validate_index */

/** @} */
