/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef VOLUMEOCCUPANCYREPORT_H
#define VOLUMEOCCUPANCYREPORT_H

/* function declarations */
void init_volumeOccupancyReport(void);
Netsnmp_Node_Handler handle_volumeOccupancySequence;
Netsnmp_Node_Handler handle_volumeOccupancyPeriod;
Netsnmp_Node_Handler handle_activeVolumeOccupancyDetectors;
Netsnmp_Node_Handler handle_volumeOccupancyPeriodV3;
Netsnmp_Node_Handler handle_detectorSampleTime;
Netsnmp_Node_Handler handle_detectorSampleDuration;

#endif /* VOLUMEOCCUPANCYREPORT_H */
