/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "driverModule.h"
#include "utils.h"
#include "defs_cpu.h"
#include "myNotifications.h"

uint16_t driverModuleStatus = 0;
uint16_t currDriverModuleStatus = DRIVER_MODULE_DUMMY_VAL;


void* get_driver_module_status(){    
    message_t* msg_ptr = &snmp_message_buf;
    memset(msg_ptr, 0, sizeof(message_t));

    msg_ptr->cmd_buffer[0] = ASIST_CMD_GET_MODULE_COMM_FAIL_STATES;
    msg_ptr->cmd_buffer[1] = 2; // mtOutcard
    msg_ptr->cmd_size      = 2;
    send_read_message(msg_ptr);

    if(msg_ptr->resp_buffer[3] == ASIST_CMD_GET_MODULE_COMM_FAIL_STATES){
        uint16_t* insert_ptr = (uint16_t*)&msg_ptr->resp_buffer[5];
        uint16_t* fail_ptr   = (uint16_t*)&msg_ptr->resp_buffer[7];

        driverModuleStatus = *insert_ptr & (*fail_ptr);
    }


    return &driverModuleStatus;
}


/** Initializes the driverModule module */
void
init_driverModule(void)
{
    const oid driverModuleStatus_oid[] = { 1,3,6,1,4,1,59873,4,2,1,1,1 };

  DEBUGMSGTL(("driverModule", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("driverModuleStatus", handle_driverModuleStatus,
                               driverModuleStatus_oid, OID_LENGTH(driverModuleStatus_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_driverModuleStatus(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     get_driver_module_status(),
                                     sizeof(driverModuleStatus));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_driverModuleStatus\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


void check_driverModule_traps(){
    get_driver_module_status();

    if(currDriverModuleStatus != driverModuleStatus){
        if(currDriverModuleStatus != DRIVER_MODULE_DUMMY_VAL)
            send_driverModuleTrap_trap(driverModuleStatus);
        currDriverModuleStatus = driverModuleStatus;
    }
}