/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "pedestrianDetectorTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement pedestrianDetectorTable get routines.
 * TODO:240:M: Implement pedestrianDetectorTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pedestrianDetectorTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::pedestrianDetectorTable is subid 7 of detector.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.7, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement pedestrianDetectorTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param pedestrianDetectorNumber_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
pedestrianDetectorTable_indexes_set_tbl_idx(pedestrianDetectorTable_mib_index *tbl_idx, long pedestrianDetectorNumber_val)
{
    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianDetectorTable_indexes_set_tbl_idx","called\n"));

    /* pedestrianDetectorNumber(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->pedestrianDetectorNumber = pedestrianDetectorNumber_val;
    

    return MFD_SUCCESS;
} /* pedestrianDetectorTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
pedestrianDetectorTable_indexes_set(pedestrianDetectorTable_rowreq_ctx *rowreq_ctx, long pedestrianDetectorNumber_val)
{
    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianDetectorTable_indexes_set","called\n"));

    if(MFD_SUCCESS != pedestrianDetectorTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , pedestrianDetectorNumber_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != pedestrianDetectorTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* pedestrianDetectorTable_indexes_set */


/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorEntry.pedestrianDetectorCallPhase
 * pedestrianDetectorCallPhase is subid 2 of pedestrianDetectorEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.7.1.2
 * Description:
<Definition> This object contains assigned phase number
for the pedestrian detector input associated with this row. The
associated detector call capability is enabled when this object
is set to a non-zero value. The value shall not exceed the value
of maxPhases.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.7.1.2
<Unit> phase
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianDetectorCallPhase data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianDetectorCallPhase_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianDetectorCallPhase_get( pedestrianDetectorTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorCallPhase_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianDetectorCallPhase_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianDetectorCallPhase_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianDetectorCallPhase data.
 * copy (* pedestrianDetectorCallPhase_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianDetectorCallPhase_val_ptr ) = rowreq_ctx->data.pedestrianDetectorCallPhase;

    return MFD_SUCCESS;
} /* pedestrianDetectorCallPhase_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorEntry.pedestrianDetectorNoActivity
 * pedestrianDetectorNoActivity is subid 3 of pedestrianDetectorEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.7.1.3
 * Description:
<Definition> Pedestrian Detector No Activity diagnostic
Parameter in minutes (0�255 min.). If an active detector does not
exhibit an actuation in the specified period, it is considered a
fault by the diagnostics and the detector is classified as
Failed. A value of 0 for this object shall disable this
diagnostic for this detector.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.7.1.3
<Unit> minute
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianDetectorNoActivity data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianDetectorNoActivity_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianDetectorNoActivity_get( pedestrianDetectorTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorNoActivity_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianDetectorNoActivity_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianDetectorNoActivity_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianDetectorNoActivity data.
 * copy (* pedestrianDetectorNoActivity_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianDetectorNoActivity_val_ptr ) = rowreq_ctx->data.pedestrianDetectorNoActivity;

    return MFD_SUCCESS;
} /* pedestrianDetectorNoActivity_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorEntry.pedestrianDetectorMaxPresence
 * pedestrianDetectorMaxPresence is subid 4 of pedestrianDetectorEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.7.1.4
 * Description:
<Definition> Pedestrian Detector Maximum Presence
diagnostic Parameter in minutes (0-255 min.). If an active
detector exhibits continuous detection for too long a period, it
is considered a fault by the diagnostics and the detector is
classified as Failed. A value of 0 for this object shall disable
this diagnostic for this detector.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.7.1.4
<Unit> minute
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianDetectorMaxPresence data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianDetectorMaxPresence_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianDetectorMaxPresence_get( pedestrianDetectorTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorMaxPresence_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianDetectorMaxPresence_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianDetectorMaxPresence_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianDetectorMaxPresence data.
 * copy (* pedestrianDetectorMaxPresence_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianDetectorMaxPresence_val_ptr ) = rowreq_ctx->data.pedestrianDetectorMaxPresence;

    return MFD_SUCCESS;
} /* pedestrianDetectorMaxPresence_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorEntry.pedestrianDetectorErraticCounts
 * pedestrianDetectorErraticCounts is subid 5 of pedestrianDetectorEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.7.1.5
 * Description:
<Definition> Pedestrian Detector Erratic Counts diagnostic
Parameter in counts/minute (0-255 cpm). If an active detector
exhibits excessive actuations, it is considered a fault by the
diagnostics and the detector is classified as Failed. A value of
0 for this object shall disable this diagnostic for this
detector.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.7.1.5
<Unit> count
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianDetectorErraticCounts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianDetectorErraticCounts_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianDetectorErraticCounts_get( pedestrianDetectorTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorErraticCounts_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianDetectorErraticCounts_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianDetectorErraticCounts_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianDetectorErraticCounts data.
 * copy (* pedestrianDetectorErraticCounts_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianDetectorErraticCounts_val_ptr ) = rowreq_ctx->data.pedestrianDetectorErraticCounts;

    return MFD_SUCCESS;
} /* pedestrianDetectorErraticCounts_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorEntry.pedestrianDetectorAlarms
 * pedestrianDetectorAlarms is subid 6 of pedestrianDetectorEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.7.1.6
 * Description:
<Definition> This object shall return indications of
detector alarms. Detector Alarms are indicated as follows (0 =
False, 1 = True):
Bit 7: Other Fault - The detector has failed due to some other
cause.
Bit 6: Reserved.
Bit 5: Reserved.
Bit 4: Configuration Fault - Detector is assigned but is not
supported.
Bit 3: Communications Fault - Communications to the device (if
present) have failed.
Bit 2: Erratic Output Fault - This detector has been flagged as
non-operational due to erratic outputs (excessive counts)
by the CU detector diagnostic.
Bit 1: Max Presence Fault - This detector has been flagged as
non-operational due to a presence indicator that exceeded
the maximum expected time by the CU detector diagnostic.
Bit 0: No Activity Fault - This detector has been flagged as non-
operational due to lower than expected activity by the CU
detector diagnostic
Once set a bit shall maintain its state as long as the condition
exists. The bit shall clear when the condition no longer exists.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.7.1.6
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianDetectorAlarms data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianDetectorAlarms_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianDetectorAlarms_get( pedestrianDetectorTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorAlarms_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianDetectorAlarms_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianDetectorAlarms_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianDetectorAlarms data.
 * copy (* pedestrianDetectorAlarms_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianDetectorAlarms_val_ptr ) = rowreq_ctx->data.pedestrianDetectorAlarms;

    return MFD_SUCCESS;
} /* pedestrianDetectorAlarms_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorEntry.pedestrianDetectorReset
 * pedestrianDetectorReset is subid 7 of pedestrianDetectorEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.7.1.7
 * Description:
<Definition> This object when set to TRUE (one) shall
cause the CU to command the associated detector to reset. This
object shall automatically return to FALSE (zero) after the CU
has issued the reset command.
Note: this may affect other detector (detector channels) that are
physically attached to a common reset line.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.7.1.7
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *   defval: 0
 *
 * Ranges:  0 - 1;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianDetectorReset data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianDetectorReset_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianDetectorReset_get( pedestrianDetectorTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorReset_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianDetectorReset_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianDetectorReset_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianDetectorReset data.
 * copy (* pedestrianDetectorReset_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianDetectorReset_val_ptr ) = rowreq_ctx->data.pedestrianDetectorReset;

    return MFD_SUCCESS;
} /* pedestrianDetectorReset_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorEntry.pedestrianButtonPushTime
 * pedestrianButtonPushTime is subid 8 of pedestrianDetectorEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.7.1.8
 * Description:
<Definition> The minimum amount of time, in tenths of a
second, a pedestrian call button is pressed to actuate additional
accessible features such as increased pedestrian crossing times
(phasePedAlternateWalk) or pedestrian clearance times
(phasePedAlternateClearance). A value of 0 indicates that all
accessible pedestrian signal (APS) features are disabled for the
associated detector.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.7.1.8
<Unit> tenth of a second
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *   defval: 0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianButtonPushTime data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianButtonPushTime_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianButtonPushTime_get( pedestrianDetectorTable_rowreq_ctx *rowreq_ctx, long * pedestrianButtonPushTime_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianButtonPushTime_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianButtonPushTime_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianButtonPushTime data.
 * copy (* pedestrianButtonPushTime_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianButtonPushTime_val_ptr ) = rowreq_ctx->data.pedestrianButtonPushTime;

    return MFD_SUCCESS;
} /* pedestrianButtonPushTime_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorEntry.pedestrianDetectorOptions
 * pedestrianDetectorOptions is subid 9 of pedestrianDetectorEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.7.1.9
 * Description:
 <Definition> Pedestrian Detector Options Parameter as
follows (0=Disabled, 1=Enabled):
Bit 7: Reserved.
Bit 6: Reserved.
Bit 5: Reserved.
Bit 4: Reserved.
Bit 3: Reserved.
Bit 2: Non-locking: If enabled, detector will place a non-locked
calls instead  of a locked calls.
Bit 1: Alternate timing: If enabled, detector will place calls
for alternate ped timing instead of normal ped timing.
Bit 0: Presence: If enabled, detector indicates presence of
pedestrians in the crosswalk instead of placing calls for
service.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.7.1.9
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *   defval: 0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianDetectorOptions data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianDetectorOptions_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianDetectorOptions_get( pedestrianDetectorTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorOptions_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianDetectorOptions_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorTable:pedestrianDetectorOptions_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianDetectorOptions data.
 * copy (* pedestrianDetectorOptions_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianDetectorOptions_val_ptr ) = rowreq_ctx->data.pedestrianDetectorOptions;

    return MFD_SUCCESS;
} /* pedestrianDetectorOptions_get */



/** @} */
