/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef SIGNALSTATETABLE_DATA_ACCESS_H
#define SIGNALSTATETABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table signalStateTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * kgm-ortak::signalStateTable is subid 2 of signalState.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.59873.4.2.1.4.2, length: 12
*/


    int signalStateTable_init_data(signalStateTable_registration * signalStateTable_reg);


    /*
     * TODO:180:o: Review signalStateTable cache timeout.
     * The number of seconds before the cache times out
     */
#define SIGNALSTATETABLE_CACHE_TIMEOUT   1

void signalStateTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void signalStateTable_container_shutdown(netsnmp_container *container_ptr);

int signalStateTable_container_load(netsnmp_container *container);
void signalStateTable_container_free(netsnmp_container *container);

int signalStateTable_cache_load(netsnmp_container *container);
void signalStateTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int signalStateTable_row_prep( signalStateTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* SIGNALSTATETABLE_DATA_ACCESS_H */
