/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef CHANNEL_1202_H
#define CHANNEL_1202_H

/* function declarations */
void init_channel_1202(void);
Netsnmp_Node_Handler handle_maxChannels;
Netsnmp_Node_Handler handle_maxChannelStatusGroups;

#endif /* CHANNEL_1202_H */
