/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file pedestrianDetectorControlGroupTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef PEDESTRIANDETECTORCONTROLGROUPTABLE_DATA_GET_H
#define PEDESTRIANDETECTORCONTROLGROUPTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pedestrianDetectorControlGroupTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::pedestrianDetectorControlGroupTable is subid 13 of detector.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.13, length: 12
*/
    /*
     * indexes
     */

    int pedestrianDetectorControlGroupActuation_get( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorControlGroupActuation_val_ptr );
    int pedestrianDetectorControlGroupNumber_get(pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx, long *pedestrianDetectorControlGroupNumber_val_ptr);
   
    //int pedestrianDetectorControlGroupReset_get(pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx, long *val);
   // int pedestrianDetectorControlGroupClear_get(pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx, long *val);
    

int pedestrianDetectorControlGroupTable_indexes_set_tbl_idx(pedestrianDetectorControlGroupTable_mib_index *tbl_idx, long pedestrianDetectorControlGroupNumber_val);
int pedestrianDetectorControlGroupTable_indexes_set(pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx, long pedestrianDetectorControlGroupNumber_val);




#ifdef __cplusplus
}
#endif

#endif /* PEDESTRIANDETECTORCONTROLGROUPTABLE_DATA_GET_H */
/** @} */
