/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-set.m2c
 */
#ifndef PEDESTRIANDETECTORCONTROLGROUPTABLE_DATA_SET_H
#define PEDESTRIANDETECTORCONTROLGROUPTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pedestrianDetectorControlGroupTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::pedestrianDetectorControlGroupTable is subid 13 of detector.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.13, length: 12
*/


int pedestrianDetectorControlGroupTable_undo_setup( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx);
int pedestrianDetectorControlGroupTable_undo_cleanup( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx);
int pedestrianDetectorControlGroupTable_undo( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx);
int pedestrianDetectorControlGroupTable_commit( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx);
int pedestrianDetectorControlGroupTable_undo_commit( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx);


int pedestrianDetectorControlGroupActuation_check_value( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx, long pedestrianDetectorControlGroupActuation_val);
int pedestrianDetectorControlGroupActuation_undo_setup( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx );
int pedestrianDetectorControlGroupActuation_set( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx, long pedestrianDetectorControlGroupActuation_val );
int pedestrianDetectorControlGroupActuation_undo( pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx );


int pedestrianDetectorControlGroupTable_check_dependencies(pedestrianDetectorControlGroupTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* PEDESTRIANDETECTORCONTROLGROUPTABLE_DATA_SET_H */
