/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef PEDESTRIANDETECTORCONTROLGROUPTABLE_INTERFACE_H
#define PEDESTRIANDETECTORCONTROLGROUPTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "pedestrianDetectorControlGroupTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _pedestrianDetectorControlGroupTable_initialize_interface(pedestrianDetectorControlGroupTable_registration * user_ctx,
    u_long flags);
void _pedestrianDetectorControlGroupTable_shutdown_interface(pedestrianDetectorControlGroupTable_registration * user_ctx);

pedestrianDetectorControlGroupTable_registration *
pedestrianDetectorControlGroupTable_registration_get( void );

pedestrianDetectorControlGroupTable_registration *
pedestrianDetectorControlGroupTable_registration_set( pedestrianDetectorControlGroupTable_registration * newreg );

netsnmp_container *pedestrianDetectorControlGroupTable_container_get( void );
int pedestrianDetectorControlGroupTable_container_size( void );

u_int pedestrianDetectorControlGroupTable_dirty_get( void );
void pedestrianDetectorControlGroupTable_dirty_set( u_int status );

pedestrianDetectorControlGroupTable_rowreq_ctx * pedestrianDetectorControlGroupTable_allocate_rowreq_ctx(void *);
void pedestrianDetectorControlGroupTable_release_rowreq_ctx(pedestrianDetectorControlGroupTable_rowreq_ctx *rowreq_ctx);

int pedestrianDetectorControlGroupTable_index_to_oid(netsnmp_index *oid_idx,
pedestrianDetectorControlGroupTable_mib_index *mib_idx);
int pedestrianDetectorControlGroupTable_index_from_oid(netsnmp_index *oid_idx,
pedestrianDetectorControlGroupTable_mib_index *mib_idx);

/* *********************************************************************
* Persistent declarations
*/
/*
* persistence
*/
#define LINE_TERM_CHAR '$'

void pedestrianDetectorControlGroupTable_container_init_persistence( netsnmp_container * container );
int pedestrianDetectorControlGroupTable_container_should_save(pedestrianDetectorControlGroupTable_rowreq_ctx * rowreq_ctx);


/*
* access to certain internals. use with caution!
*/
void pedestrianDetectorControlGroupTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* PEDESTRIANDETECTORCONTROLGROUPTABLE_INTERFACE_H */
/** @} */