/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file phaseStatusGroupTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef PHASESTATUSGROUPTABLE_DATA_GET_H
#define PHASESTATUSGROUPTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table phaseStatusGroupTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::phaseStatusGroupTable is subid 4 of phase.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.1.4, length: 12
*/
    /*
     * indexes
     */

    int phaseStatusGroupReds_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupReds_val_ptr );
    int phaseStatusGroupYellows_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupYellows_val_ptr );
    int phaseStatusGroupGreens_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupGreens_val_ptr );
    int phaseStatusGroupDontWalks_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupDontWalks_val_ptr );
    int phaseStatusGroupPedClears_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupPedClears_val_ptr );
    int phaseStatusGroupWalks_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupWalks_val_ptr );
    int phaseStatusGroupVehCalls_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupVehCalls_val_ptr );
    int phaseStatusGroupPedCalls_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupPedCalls_val_ptr );
    int phaseStatusGroupPhaseOns_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupPhaseOns_val_ptr );
    int phaseStatusGroupPhaseNexts_get( phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long * phaseStatusGroupPhaseNexts_val_ptr );


int phaseStatusGroupTable_indexes_set_tbl_idx(phaseStatusGroupTable_mib_index *tbl_idx, long phaseStatusGroupNumber_val);
int phaseStatusGroupTable_indexes_set(phaseStatusGroupTable_rowreq_ctx *rowreq_ctx, long phaseStatusGroupNumber_val);




#ifdef __cplusplus
}
#endif

#endif /* PHASESTATUSGROUPTABLE_DATA_GET_H */
/** @} */
