/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef PHASESTATUSGROUPTABLE_OIDS_H
#define PHASESTATUSGROUPTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table phaseStatusGroupTable */
#define PHASESTATUSGROUPTABLE_OID              1,3,6,1,4,1,1206,4,2,1,1,4


#define COLUMN_PHASESTATUSGROUPNUMBER         1
    
#define COLUMN_PHASESTATUSGROUPREDS         2
    
#define COLUMN_PHASESTATUSGROUPYELLOWS         3
    
#define COLUMN_PHASESTATUSGROUPGREENS         4
    
#define COLUMN_PHASESTATUSGROUPDONTWALKS         5
    
#define COLUMN_PHASESTATUSGROUPPEDCLEARS         6
    
#define COLUMN_PHASESTATUSGROUPWALKS         7
    
#define COLUMN_PHASESTATUSGROUPVEHCALLS         8
    
#define COLUMN_PHASESTATUSGROUPPEDCALLS         9
    
#define COLUMN_PHASESTATUSGROUPPHASEONS         10
    
#define COLUMN_PHASESTATUSGROUPPHASENEXTS         11
    

#define PHASESTATUSGROUPTABLE_MIN_COL   COLUMN_PHASESTATUSGROUPNUMBER
#define PHASESTATUSGROUPTABLE_MAX_COL   COLUMN_PHASESTATUSGROUPPHASENEXTS
    


#ifdef __cplusplus
}
#endif

#endif /* PHASESTATUSGROUPTABLE_OIDS_H */
