/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "utils.h"
#include "detector_parameters_data.h"

/** Initializes the detector module */
void
init_detector_1202(void)
{
  
    const oid maxVehicleDetectors_oid[] = { 1,3,6,1,4,1,1206,4,2,1,2,1 };
    const oid maxVehicleDetectorStatusGroups_oid[] = { 1,3,6,1,4,1,1206,4,2,1,2,3 };
    const oid maxVehicleDetectorControlGroups_oid[] = { 1,3,6,1,4,1,1206,4,2,1,2,11 };
    const oid maxPedestrianDetectors_oid[] = { 1,3,6,1,4,1,1206,4,2,1,2,6 };
    const oid maxPedestrianDetectorGroups_oid[] = { 1,3,6,1,4,1,1206,4,2,1,2,8 };


  DEBUGMSGTL(("detector", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("maxVehicleDetectors", handle_maxVehicleDetectors,
                               maxVehicleDetectors_oid, OID_LENGTH(maxVehicleDetectors_oid),
                               HANDLER_CAN_RONLY
        ));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("maxVehicleDetectorStatusGroups", handle_maxVehicleDetectorStatusGroups,
                               maxVehicleDetectorStatusGroups_oid, OID_LENGTH(maxVehicleDetectorStatusGroups_oid),
                               HANDLER_CAN_RONLY
        ));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("maxPedestrianDetectors", handle_maxPedestrianDetectors,
                               maxPedestrianDetectors_oid, OID_LENGTH(maxPedestrianDetectors_oid),
                               HANDLER_CAN_RONLY
        ));

 
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("maxPedestrianDetectorGroups", handle_maxPedestrianDetectorGroups,
                               maxPedestrianDetectorGroups_oid, OID_LENGTH(maxPedestrianDetectorGroups_oid),
                               HANDLER_CAN_RONLY
        ));
 

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("maxVehicleDetectorControlGroups", handle_maxVehicleDetectorControlGroups,
                               maxVehicleDetectorControlGroups_oid, OID_LENGTH(maxVehicleDetectorControlGroups_oid),
                               HANDLER_CAN_RONLY
        ));
}


int
handle_maxVehicleDetectors(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     get_maxVehicleDetectorNumber(),
                                     sizeof(int));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_maxVehicleDetectors\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_maxVehicleDetectorStatusGroups(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     get_maxVehicleDetectorStatusGroup(1),
                                     sizeof(int));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_maxVehicleDetectorStatusGroups\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


int
handle_maxPedestrianDetectors(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     get_maxPedestrianDetectorNumber(),
                                     sizeof(int));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_maxPedestrianDetectors\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_maxPedestrianDetectorGroups(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     get_maxPedestrianDetectorStatusGroup(2),
                                     sizeof(int));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_maxPedestrianDetectorGroups\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


int
handle_maxVehicleDetectorControlGroups(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     get_maxVehicleDetectorControlGroupNumber(),
                                     sizeof(int));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_maxPedestrianDetectorGroups\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}