/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
#ifndef PEDESTRIANDETECTORSTATUSGROUPTABLE_H
#define PEDESTRIANDETECTORSTATUSGROUPTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(NTCIP1202-v03);
config_require(NTCIP1202-v03/pedestrianDetectorStatusGroupTable/pedestrianDetectorStatusGroupTable_interface);
config_require(NTCIP1202-v03/pedestrianDetectorStatusGroupTable/pedestrianDetectorStatusGroupTable_data_access);
config_require(NTCIP1202-v03/pedestrianDetectorStatusGroupTable/pedestrianDetectorStatusGroupTable_data_get);
config_require(NTCIP1202-v03/pedestrianDetectorStatusGroupTable/pedestrianDetectorStatusGroupTable_data_set);
    /* *INDENT-ON*  */

/* OID and column number definitions for pedestrianDetectorStatusGroupTable */
#include "pedestrianDetectorStatusGroupTable_oids.h"

/* enum definions */
#include "pedestrianDetectorStatusGroupTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_pedestrianDetectorStatusGroupTable(void);
void shutdown_pedestrianDetectorStatusGroupTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pedestrianDetectorStatusGroupTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::pedestrianDetectorStatusGroupTable is subid 9 of detector.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.9, length: 12
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review pedestrianDetectorStatusGroupTable registration context.
     */
typedef netsnmp_data_list pedestrianDetectorStatusGroupTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review pedestrianDetectorStatusGroupTable data context structure.
 * This structure is used to represent the data for pedestrianDetectorStatusGroupTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * pedestrianDetectorStatusGroupTable.
 */
typedef struct pedestrianDetectorStatusGroupTable_data_s {
    
        /*
         * pedestrianDetectorStatusGroupActive(2)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   pedestrianDetectorStatusGroupActive;
    
        /*
         * pedestrianDetectorStatusGroupAlarms(3)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   pedestrianDetectorStatusGroupAlarms;
    
} pedestrianDetectorStatusGroupTable_data;


/*
 * TODO:120:r: |-> Review pedestrianDetectorStatusGroupTable mib index.
 * This structure is used to represent the index for pedestrianDetectorStatusGroupTable.
 */
typedef struct pedestrianDetectorStatusGroupTable_mib_index_s {

        /*
         * pedestrianDetectorStatusGroupNumber(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   pedestrianDetectorStatusGroupNumber;


} pedestrianDetectorStatusGroupTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review pedestrianDetectorStatusGroupTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_pedestrianDetectorStatusGroupTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review pedestrianDetectorStatusGroupTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * pedestrianDetectorStatusGroupTable_rowreq_ctx pointer.
 */
typedef struct pedestrianDetectorStatusGroupTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_pedestrianDetectorStatusGroupTable_IDX_LEN];
    
    pedestrianDetectorStatusGroupTable_mib_index        tbl_idx;
    
    pedestrianDetectorStatusGroupTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to pedestrianDetectorStatusGroupTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *pedestrianDetectorStatusGroupTable_data_list;

} pedestrianDetectorStatusGroupTable_rowreq_ctx;

typedef struct pedestrianDetectorStatusGroupTable_ref_rowreq_ctx_s {
    pedestrianDetectorStatusGroupTable_rowreq_ctx *rowreq_ctx;
} pedestrianDetectorStatusGroupTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int pedestrianDetectorStatusGroupTable_pre_request(pedestrianDetectorStatusGroupTable_registration * user_context);
    int pedestrianDetectorStatusGroupTable_post_request(pedestrianDetectorStatusGroupTable_registration * user_context,
        int rc);

    int pedestrianDetectorStatusGroupTable_rowreq_ctx_init(pedestrianDetectorStatusGroupTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void pedestrianDetectorStatusGroupTable_rowreq_ctx_cleanup(pedestrianDetectorStatusGroupTable_rowreq_ctx *rowreq_ctx);


    pedestrianDetectorStatusGroupTable_rowreq_ctx *
                  pedestrianDetectorStatusGroupTable_row_find_by_mib_index(pedestrianDetectorStatusGroupTable_mib_index *mib_idx);

extern const oid pedestrianDetectorStatusGroupTable_oid[];
extern const int pedestrianDetectorStatusGroupTable_oid_size;


#include "pedestrianDetectorStatusGroupTable_interface.h"
#include "pedestrianDetectorStatusGroupTable_data_access.h"
#include "pedestrianDetectorStatusGroupTable_data_get.h"
#include "pedestrianDetectorStatusGroupTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* PEDESTRIANDETECTORSTATUSGROUPTABLE_H */
/** @} */
