/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 * 
 * semıh isikyidiz 
 * Bu dosya snmp ye veri döndürmek için kullanılır.
 * 
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "pedestrianDetectorStatusGroupTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement pedestrianDetectorStatusGroupTable get routines.
 * TODO:240:M: Implement pedestrianDetectorStatusGroupTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pedestrianDetectorStatusGroupTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::pedestrianDetectorStatusGroupTable is subid 9 of detector.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.9, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement pedestrianDetectorStatusGroupTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param pedestrianDetectorStatusGroupNumber_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
pedestrianDetectorStatusGroupTable_indexes_set_tbl_idx(pedestrianDetectorStatusGroupTable_mib_index *tbl_idx, long pedestrianDetectorStatusGroupNumber_val)
{
    DEBUGMSGTL(("verbose:pedestrianDetectorStatusGroupTable:pedestrianDetectorStatusGroupTable_indexes_set_tbl_idx","called\n"));

    /* pedestrianDetectorStatusGroupNumber(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->pedestrianDetectorStatusGroupNumber = pedestrianDetectorStatusGroupNumber_val;
    

    return MFD_SUCCESS;
} /* pedestrianDetectorStatusGroupTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
pedestrianDetectorStatusGroupTable_indexes_set(pedestrianDetectorStatusGroupTable_rowreq_ctx *rowreq_ctx, long pedestrianDetectorStatusGroupNumber_val)
{
    DEBUGMSGTL(("verbose:pedestrianDetectorStatusGroupTable:pedestrianDetectorStatusGroupTable_indexes_set","called\n"));

    if(MFD_SUCCESS != pedestrianDetectorStatusGroupTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , pedestrianDetectorStatusGroupNumber_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != pedestrianDetectorStatusGroupTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* pedestrianDetectorStatusGroupTable_indexes_set */


/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorStatusGroupEntry.pedestrianDetectorStatusGroupActive
 * pedestrianDetectorStatusGroupActive is subid 2 of pedestrianDetectorStatusGroupEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.9.1.2
 * Description:
<Definition>This object shall return the detection status
of each pedestrian detector associated with the group. Each
detector shall be represented as ON (detect) or OFF (no-detect)
by individual bits in this object. If a detector is ON then the
associated bit shall be set (1). If a detector is OFF then the
associated bit shall be clear (0).
Bit 7: Det # = ( pedestrianDetectorStatusGroupNumber * 8)
Bit 6: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 1
Bit 5: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 2
Bit 4: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 3
Bit 3: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 4
Bit 2: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 5
Bit 1: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 6
Bit 0: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 7
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.9.1.2
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianDetectorStatusGroupActive data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianDetectorStatusGroupActive_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianDetectorStatusGroupActive_get( pedestrianDetectorStatusGroupTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorStatusGroupActive_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianDetectorStatusGroupActive_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorStatusGroupTable:pedestrianDetectorStatusGroupActive_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianDetectorStatusGroupActive data.
 * copy (* pedestrianDetectorStatusGroupActive_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianDetectorStatusGroupActive_val_ptr ) = rowreq_ctx->data.pedestrianDetectorStatusGroupActive;

    return MFD_SUCCESS;
} /* pedestrianDetectorStatusGroupActive_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::pedestrianDetectorStatusGroupEntry.pedestrianDetectorStatusGroupAlarms
 * pedestrianDetectorStatusGroupAlarms is subid 3 of pedestrianDetectorStatusGroupEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.9.1.3
 * Description:
<Definition> This object shall return the alarm status of
the pedestrian detectors associated with the group. Each
pedestrian detector alarm status shall be represented as ON or
OFF by individual bits in this object. If any pedestrian detector
alarm (defined in the pedestrianDetectorAlarms object) is active
the associated bit shall be set (1). If a pedestrian detector
alarm is not active the associated bit shall be clear (0).
Bit 7: Det # = ( pedestrianDetectorStatusGroupNumber * 8)
Bit 6: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 1
Bit 5: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 2
Bit 4: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 3
Bit 3: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 4
Bit 2: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 5
Bit 1: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 6
Bit 0: Det # = ( pedestrianDetectorStatusGroupNumber * 8) - 7
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.9.1.3
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the pedestrianDetectorStatusGroupAlarms data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pedestrianDetectorStatusGroupAlarms_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pedestrianDetectorStatusGroupAlarms_get( pedestrianDetectorStatusGroupTable_rowreq_ctx *rowreq_ctx, long * pedestrianDetectorStatusGroupAlarms_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pedestrianDetectorStatusGroupAlarms_val_ptr );


    DEBUGMSGTL(("verbose:pedestrianDetectorStatusGroupTable:pedestrianDetectorStatusGroupAlarms_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pedestrianDetectorStatusGroupAlarms data.
 * copy (* pedestrianDetectorStatusGroupAlarms_val_ptr ) from rowreq_ctx->data
 */
    (* pedestrianDetectorStatusGroupAlarms_val_ptr ) = rowreq_ctx->data.pedestrianDetectorStatusGroupAlarms;

    return MFD_SUCCESS;
} /* pedestrianDetectorStatusGroupAlarms_get */



/** @} */
