/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef GLOBALMODULETABLE_INTERFACE_H
#define GLOBALMODULETABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "globalModuleTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _globalModuleTable_initialize_interface(globalModuleTable_registration * user_ctx,
                                    u_long flags);
void _globalModuleTable_shutdown_interface(globalModuleTable_registration * user_ctx);

globalModuleTable_registration *
globalModuleTable_registration_get( void );

globalModuleTable_registration *
globalModuleTable_registration_set( globalModuleTable_registration * newreg );

netsnmp_container *globalModuleTable_container_get( void );
int globalModuleTable_container_size( void );

    globalModuleTable_rowreq_ctx * globalModuleTable_allocate_rowreq_ctx(void *);
void globalModuleTable_release_rowreq_ctx(globalModuleTable_rowreq_ctx *rowreq_ctx);

int globalModuleTable_index_to_oid(netsnmp_index *oid_idx,
                            globalModuleTable_mib_index *mib_idx);
int globalModuleTable_index_from_oid(netsnmp_index *oid_idx,
                              globalModuleTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void globalModuleTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* GLOBALMODULETABLE_INTERFACE_H */
/** @} */
