/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef GLOBALMODULETABLE_DATA_ACCESS_H
#define GLOBALMODULETABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table globalModuleTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1201-v03::globalModuleTable is subid 3 of globalConfiguration.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.6.1.3, length: 12
*/


    int globalModuleTable_init_data(globalModuleTable_registration * globalModuleTable_reg);


    /*
     * TODO:180:o: Review globalModuleTable cache timeout.
     * The number of seconds before the cache times out
     */
#define GLOBALMODULETABLE_CACHE_TIMEOUT   1

void globalModuleTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void globalModuleTable_container_shutdown(netsnmp_container *container_ptr);

int globalModuleTable_container_load(netsnmp_container *container);
void globalModuleTable_container_free(netsnmp_container *container);

int globalModuleTable_cache_load(netsnmp_container *container);
void globalModuleTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int globalModuleTable_row_prep( globalModuleTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* GLOBALMODULETABLE_DATA_ACCESS_H */
