/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "globalModuleTable.h"


#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "globalModuleTable_interface.h"

netsnmp_feature_require(baby_steps);
netsnmp_feature_require(row_merge);
netsnmp_feature_require(check_all_requests_error);

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table globalModuleTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1201-v03::globalModuleTable is subid 3 of globalConfiguration.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.6.1.3, length: 12
*/
typedef struct globalModuleTable_interface_ctx_s {

   netsnmp_container              *container;
   netsnmp_cache                  *cache;

   globalModuleTable_registration *      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

} globalModuleTable_interface_ctx;

static globalModuleTable_interface_ctx globalModuleTable_if_ctx;

static void _globalModuleTable_container_init(
    globalModuleTable_interface_ctx *if_ctx);
static void _globalModuleTable_container_shutdown(
    globalModuleTable_interface_ctx *if_ctx);


netsnmp_container *
globalModuleTable_container_get( void )
{
    return globalModuleTable_if_ctx.container;
}

globalModuleTable_registration *
globalModuleTable_registration_get( void )
{
    return globalModuleTable_if_ctx.user_ctx;
}

globalModuleTable_registration *
globalModuleTable_registration_set( globalModuleTable_registration * newreg )
{
    globalModuleTable_registration * old = globalModuleTable_if_ctx.user_ctx;
    globalModuleTable_if_ctx.user_ctx = newreg;
    return old;
}

int
globalModuleTable_container_size( void )
{
    return CONTAINER_SIZE(globalModuleTable_if_ctx.container);
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_globalModuleTable_pre_request;
static Netsnmp_Node_Handler _mfd_globalModuleTable_post_request;
static Netsnmp_Node_Handler _mfd_globalModuleTable_object_lookup;
static Netsnmp_Node_Handler _mfd_globalModuleTable_get_values;
/**
 * @internal
 * Initialize the table globalModuleTable 
 *    (Define its contents and how it's structured)
 */
void
_globalModuleTable_initialize_interface(globalModuleTable_registration * reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &globalModuleTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &globalModuleTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:globalModuleTable:_globalModuleTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for globalModuleTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_INTEGER, /** index: moduleNumber */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrieval. */
    tbl_info->min_column = GLOBALMODULETABLE_MIN_COL;
    tbl_info->max_column = GLOBALMODULETABLE_MAX_COL;

    /*
     * save users context
     */
    globalModuleTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    globalModuleTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _globalModuleTable_container_init(&globalModuleTable_if_ctx);
    if (NULL == globalModuleTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for globalModuleTable\n");
        return;
    }
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_globalModuleTable_object_lookup;
    access_multiplexer->get_values = _mfd_globalModuleTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_globalModuleTable_pre_request;
    access_multiplexer->post_request = _mfd_globalModuleTable_post_request;

#ifndef NETSNMP_DISABLE_SET_SUPPORT
#endif

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("globalModuleTable:init_globalModuleTable",
                "Registering globalModuleTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("globalModuleTable", handler,
                                                  globalModuleTable_oid,
                                                  globalModuleTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
#if (defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
                                                  HANDLER_CAN_RONLY
#else
                                                  HANDLER_CAN_RONLY
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table globalModuleTable\n");
        return;
    }
    reginfo->my_reg_void = &globalModuleTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
#if !(defined(NETSNMP_NO_WRITE_SUPPORT) || defined(NETSNMP_DISABLE_SET_SUPPORT))
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
#endif /* NETSNMP_NO_WRITE_SUPPORT || NETSNMP_DISABLE_SET_SUPPORT */
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            globalModuleTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*************************************************
     *
     * inject cache helper
     */
    if(NULL != globalModuleTable_if_ctx.cache) {
        handler = netsnmp_cache_handler_get(globalModuleTable_if_ctx.cache);
        netsnmp_inject_handler( reginfo, handler );
    }

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);

} /* _globalModuleTable_initialize_interface */

/**
 * @internal
 * Shutdown the table globalModuleTable
 */
void
_globalModuleTable_shutdown_interface(globalModuleTable_registration * reg_ptr)
{
    /*
     * shutdown the container
     */
    _globalModuleTable_container_shutdown(&globalModuleTable_if_ctx);
}

void
globalModuleTable_valid_columns_set(netsnmp_column_info *vc)
{
    globalModuleTable_if_ctx.tbl_info.valid_columns = vc;
} /* globalModuleTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
globalModuleTable_index_to_oid(netsnmp_index *oid_idx,
                         globalModuleTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * moduleNumber(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
     */
    netsnmp_variable_list var_moduleNumber;

    /*
     * set up varbinds
     */
    memset( &var_moduleNumber, 0x00, sizeof(var_moduleNumber) );
    var_moduleNumber.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_moduleNumber.next_variable =  NULL;


    DEBUGMSGTL(("verbose:globalModuleTable:globalModuleTable_index_to_oid","called\n"));

        /* moduleNumber(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    snmp_set_var_value(&var_moduleNumber, &mib_idx->moduleNumber, sizeof(mib_idx->moduleNumber));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_moduleNumber);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_moduleNumber );

    return err;
} /* globalModuleTable_index_to_oid */

/**
 * extract globalModuleTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
globalModuleTable_index_from_oid(netsnmp_index *oid_idx,
                         globalModuleTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * moduleNumber(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
     */
    netsnmp_variable_list var_moduleNumber;

    /*
     * set up varbinds
     */
    memset( &var_moduleNumber, 0x00, sizeof(var_moduleNumber) );
    var_moduleNumber.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_moduleNumber.next_variable =  NULL;


    DEBUGMSGTL(("verbose:globalModuleTable:globalModuleTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_moduleNumber );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    mib_idx->moduleNumber = *((long *)var_moduleNumber.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_moduleNumber );

    return err;
} /* globalModuleTable_index_from_oid */


/* *********************************************************************
 * @internal
 * allocate resources for a globalModuleTable_rowreq_ctx
 */
globalModuleTable_rowreq_ctx *
globalModuleTable_allocate_rowreq_ctx(void *user_init_ctx)
{
    globalModuleTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(globalModuleTable_rowreq_ctx);

    DEBUGMSGTL(("internal:globalModuleTable:globalModuleTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "globalModuleTable_rowreq_ctx.\n");
        return NULL;
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->globalModuleTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if (!(rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER)) {
        if(SNMPERR_SUCCESS !=
            globalModuleTable_rowreq_ctx_init(rowreq_ctx, user_init_ctx)) {
           globalModuleTable_release_rowreq_ctx(rowreq_ctx);
           rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
} /* globalModuleTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a globalModuleTable_rowreq_ctx
 */
void
globalModuleTable_release_rowreq_ctx(globalModuleTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:globalModuleTable:globalModuleTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    globalModuleTable_rowreq_ctx_cleanup(rowreq_ctx);

    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* globalModuleTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_globalModuleTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc;

    DEBUGMSGTL(("internal:globalModuleTable:_mfd_globalModuleTable_pre_request",
                "called\n"));
    
    if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:globalModuleTable",
                    "skipping additional pre_request\n"));
        return SNMP_ERR_NOERROR;
    }
        
    rc = globalModuleTable_pre_request(globalModuleTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("globalModuleTable","error %d from "
                    "globalModuleTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_globalModuleTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_globalModuleTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    globalModuleTable_rowreq_ctx *rowreq_ctx = (globalModuleTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    int rc, packet_rc;

    DEBUGMSGTL(("internal:globalModuleTable:_mfd_globalModuleTable_post_request",
                "called\n"));

    /*
     * release row context, if deleted
     */
    if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
        globalModuleTable_release_rowreq_ctx(rowreq_ctx);

    /*
     * wait for last call before calling user
     */
    if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
        DEBUGMSGTL(("internal:globalModuleTable",
                    "waiting for last post_request\n"));
        return SNMP_ERR_NOERROR;
    }
    
    packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
    rc = globalModuleTable_post_request(globalModuleTable_if_ctx.user_ctx,packet_rc);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("globalModuleTable","error %d from "
                    "globalModuleTable_post_request\n", rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_globalModuleTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_globalModuleTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    int                    rc = SNMP_ERR_NOERROR;
    globalModuleTable_rowreq_ctx *rowreq_ctx = (globalModuleTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:globalModuleTable:_mfd_globalModuleTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * globalModuleTable_interface_ctx *if_ctx =
     *             (globalModuleTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        rc = SNMP_ERR_NOCREATION;
    }

    if (MFD_SUCCESS != rc)
        netsnmp_request_set_error_all(requests, rc);
    else
        globalModuleTable_row_prep(rowreq_ctx);

    return SNMP_VALIDATE_ERR(rc);
} /* _mfd_globalModuleTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_globalModuleTable_get_column( globalModuleTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:globalModuleTable:_mfd_globalModuleTable_get_column",
                "called for %d\n", column));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* (INDEX) moduleNumber(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    case COLUMN_MODULENUMBER:
    var->type = ASN_INTEGER;
        var->val_len = sizeof(long);
        (*var->val.integer) = rowreq_ctx->tbl_idx.moduleNumber;
        break;

    /* moduleDeviceNode(2)/OBJECTID/ASN_OBJECT_ID/oid(oid)//L/A/w/e/r/d/h */
    case COLUMN_MODULEDEVICENODE:
    var->type = ASN_OBJECT_ID;
rc = moduleDeviceNode_get(rowreq_ctx, (oid **)&var->val.string, &var->val_len );
        break;

    /* moduleMake(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h */
    case COLUMN_MODULEMAKE:
    var->type = ASN_OCTET_STR;
rc = moduleMake_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* moduleModel(4)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h */
    case COLUMN_MODULEMODEL:
    var->type = ASN_OCTET_STR;
rc = moduleModel_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* moduleVersion(5)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h */
    case COLUMN_MODULEVERSION:
    var->type = ASN_OCTET_STR;
rc = moduleVersion_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* moduleType(6)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_MODULETYPE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = moduleType_get(rowreq_ctx, (u_long *)var->val.string );
        break;

     default:
        if (GLOBALMODULETABLE_MIN_COL <= column && column <= GLOBALMODULETABLE_MAX_COL) {
            DEBUGMSGTL(("internal:globalModuleTable:_mfd_globalModuleTable_get_column",
                "assume column %d is reserved\n", column));
            rc = MFD_SKIP;
        } else {
            snmp_log(LOG_ERR,
                "unknown column %d in _globalModuleTable_get_column\n", column);
        }
        break;
    }

    return rc;
} /* _globalModuleTable_get_column */

int
_mfd_globalModuleTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    globalModuleTable_rowreq_ctx *rowreq_ctx = (globalModuleTable_rowreq_ctx*)
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:globalModuleTable:_mfd_globalModuleTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _globalModuleTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allocated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_globalModuleTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*
 * SET PROCESSING NOT APPLICABLE (per MIB or user setting)
 */
/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
static void _container_free(netsnmp_container *container);

/**
 * @internal
 */
static int
_cache_load(netsnmp_cache *cache, void *vmagic)
{
    DEBUGMSGTL(("internal:globalModuleTable:_cache_load","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache for globalModuleTable_cache_load\n");
        return -1;
    }

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));
    
    /*
     * call user code
     */
    return globalModuleTable_container_load((netsnmp_container*)cache->magic);
} /* _cache_load */

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache *cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:globalModuleTable:_cache_free","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache in globalModuleTable_cache_free\n");
        return;
    }

    container = (netsnmp_container*)cache->magic;

    _container_free(container);
} /* _cache_free */

/**
 * @internal
 */
static void
_container_item_free(globalModuleTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:globalModuleTable:_container_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    globalModuleTable_release_rowreq_ctx(rowreq_ctx);
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("internal:globalModuleTable:_container_free","called\n"));

    if (NULL == container) {
        snmp_log(LOG_ERR, "invalid container in globalModuleTable_container_free\n");
        return;
    }

    /*
     * call user code
     */
    globalModuleTable_container_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_container_item_free,
                    NULL);
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void
_globalModuleTable_container_init(globalModuleTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:globalModuleTable:_globalModuleTable_container_init","called\n"));

    /*
     * cache init
     */
    if_ctx->cache = netsnmp_cache_create(30, /* timeout in seconds */
                                         _cache_load, _cache_free,
                                         globalModuleTable_oid,
                                         globalModuleTable_oid_size);

    if(NULL == if_ctx->cache) {
        snmp_log(LOG_ERR, "error creating cache for globalModuleTable\n");
        return;
    }

    if_ctx->cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    globalModuleTable_container_init(&if_ctx->container, if_ctx->cache);
    if(NULL == if_ctx->container) {
        if_ctx->container = netsnmp_container_find("globalModuleTable:table_container");
        if(NULL != if_ctx->container) {
            /*
             * When reporting container management errors, we log the container's
             * name, so set it here.
             */
            if_ctx->container->container_name = strdup("globalModuleTable");
        }
    }
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "globalModuleTable_container_init\n");
        return;
    }

    if (NULL != if_ctx->cache)
        if_ctx->cache->magic = (void*)if_ctx->container;
} /* _globalModuleTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void
_globalModuleTable_container_shutdown(globalModuleTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:globalModuleTable:_globalModuleTable_container_shutdown","called\n"));

    globalModuleTable_container_shutdown(if_ctx->container);

    _container_free(if_ctx->container);

} /* _globalModuleTable_container_shutdown */


globalModuleTable_rowreq_ctx *
globalModuleTable_row_find_by_mib_index(globalModuleTable_mib_index *mib_idx)
{
    globalModuleTable_rowreq_ctx   *rowreq_ctx;
    oid                      oid_tmp[MAX_OID_LEN];
    netsnmp_index            oid_idx;
    int                      rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof(oid_tmp)/sizeof(oid);

    /*
     * convert
     */
    rc = globalModuleTable_index_to_oid(&oid_idx, mib_idx);
    if (MFD_SUCCESS != rc)
        return NULL;

    rowreq_ctx = (globalModuleTable_rowreq_ctx*)CONTAINER_FIND(globalModuleTable_if_ctx.container, &oid_idx);

    return rowreq_ctx;
}

