/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "global_config_data.h"

#include "globalModuleTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table globalModuleTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1201-v03::globalModuleTable is subid 3 of globalConfiguration.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.6.1.3, length: 12
*/

/**
 * initialization for globalModuleTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param globalModuleTable_reg
 *        Pointer to globalModuleTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
globalModuleTable_init_data(globalModuleTable_registration * globalModuleTable_reg)
{
    DEBUGMSGTL(("verbose:globalModuleTable:globalModuleTable_init_data","called\n"));

    static unsigned int global_module_table_columns[] = {
        COLUMN_MODULENUMBER,
        COLUMN_MODULEDEVICENODE,
        COLUMN_MODULEMAKE,
        COLUMN_MODULEMODEL,
        COLUMN_MODULEVERSION,
        COLUMN_MODULETYPE
    };

    static netsnmp_column_info valid_columns;
    valid_columns.isRange = 0;
    valid_columns.details.list = global_module_table_columns;
    valid_columns.list_count = sizeof(global_module_table_columns)/sizeof(unsigned int);
    globalModuleTable_valid_columns_set(&valid_columns);

    return MFD_SUCCESS;
} /* globalModuleTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
globalModuleTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache)
{
    DEBUGMSGTL(("verbose:globalModuleTable:globalModuleTable_container_init","called\n"));
    
    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,"bad container param to globalModuleTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,"bad cache param to globalModuleTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up globalModuleTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = GLOBALMODULETABLE_CACHE_TIMEOUT; /* seconds */
} /* globalModuleTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before globalModuleTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
globalModuleTable_container_shutdown(netsnmp_container *container_ptr)
{
    DEBUGMSGTL(("verbose:globalModuleTable:globalModuleTable_container_shutdown","called\n"));
    
    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,"bad params to globalModuleTable_container_shutdown\n");
        return;
    }

} /* globalModuleTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement globalModuleTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data involves more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  globalModuleTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
globalModuleTable_container_load(netsnmp_container *container)
{
    globalModuleTable_rowreq_ctx *rowreq_ctx;
    size_t                 count = 0;

    /*
     * storage for each column
     */
    long   moduleNumber;


    DEBUGMSGTL(("verbose:globalModuleTable:globalModuleTable_container_load","called\n"));

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    globalModuleTable_rowreq_ctx* table_ptr = NULL;
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    /*
     * TODO:351:M: |-> Load/update data in the globalModuleTable container.
     * loop over your globalModuleTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
    while( 1 ) {
    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    table_ptr = get_global_module_table(count);

    if(table_ptr == NULL)
        break;
    /*
     * parse line into variables
     */
    moduleNumber = table_ptr->tbl_idx.moduleNumber;
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    /*
        * TODO:352:M: |   |-> set indexes in new globalModuleTable rowreq context.
        * data context will be set from the param (unless NULL,
        *      in which case a new data context will be allocated)
        */
    rowreq_ctx = globalModuleTable_allocate_rowreq_ctx(NULL);
    if (NULL == rowreq_ctx) {
        snmp_log(LOG_ERR, "memory allocation failed\n");
        return MFD_RESOURCE_UNAVAILABLE;
    }
    if(MFD_SUCCESS != globalModuleTable_indexes_set(rowreq_ctx
                            , moduleNumber
            )) {
        snmp_log(LOG_ERR,"error setting index while loading "
                    "globalModuleTable data.\n");
        globalModuleTable_release_rowreq_ctx(rowreq_ctx);
        continue;
    }

    /*
        * TODO:352:r: |   |-> populate globalModuleTable data context.
        * Populate data context here. (optionally, delay until row prep)
        */
    /*
     * TRANSIENT or semi-TRANSIENT data:
     * copy data or save any info needed to do it in row_prep.
     */
    /*
     * setup/save data for moduleDeviceNode
     * moduleDeviceNode(2)/OBJECTID/ASN_OBJECT_ID/oid(oid)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for moduleDeviceNode data
     */
    if ((NULL == rowreq_ctx->data.moduleDeviceNode) ||
        (sizeof(rowreq_ctx->data.moduleDeviceNode) <
         (table_ptr->data.moduleDeviceNode_len* sizeof(table_ptr->data.moduleDeviceNode[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (moduleDeviceNode)\n");
        return MFD_ERROR;
    }
    rowreq_ctx->data.moduleDeviceNode_len = table_ptr->data.moduleDeviceNode_len* sizeof(table_ptr->data.moduleDeviceNode[0]);
    memcpy( rowreq_ctx->data.moduleDeviceNode, table_ptr->data.moduleDeviceNode, table_ptr->data.moduleDeviceNode_len* sizeof(table_ptr->data.moduleDeviceNode[0]) );
    
    /*
     * setup/save data for moduleMake
     * moduleMake(3)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for moduleMake data
     */
    if ((NULL == rowreq_ctx->data.moduleMake) ||
        (sizeof(rowreq_ctx->data.moduleMake) <
         (table_ptr->data.moduleMake_len* sizeof(table_ptr->data.moduleMake[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (moduleMake)\n");
        return MFD_ERROR;
    }
    rowreq_ctx->data.moduleMake_len = table_ptr->data.moduleMake_len* sizeof(table_ptr->data.moduleMake[0]);
    memcpy( rowreq_ctx->data.moduleMake, table_ptr->data.moduleMake, table_ptr->data.moduleMake_len* sizeof(table_ptr->data.moduleMake[0]) );
    
    /*
     * setup/save data for moduleModel
     * moduleModel(4)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for moduleModel data
     */
    if ((NULL == rowreq_ctx->data.moduleModel) ||
        (sizeof(rowreq_ctx->data.moduleModel) <
         (table_ptr->data.moduleModel_len* sizeof(table_ptr->data.moduleModel[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (moduleModel)\n");
        return MFD_ERROR;
    }
    rowreq_ctx->data.moduleModel_len = table_ptr->data.moduleModel_len* sizeof(table_ptr->data.moduleModel[0]);
    memcpy( rowreq_ctx->data.moduleModel, table_ptr->data.moduleModel, table_ptr->data.moduleModel_len* sizeof(table_ptr->data.moduleModel[0]) );
    
    /*
     * setup/save data for moduleVersion
     * moduleVersion(5)/OCTETSTR/ASN_OCTET_STR/char(char)//L/A/w/e/r/d/h
     */
    /** no mapping */
    /*
     * make sure there is enough space for moduleVersion data
     */
    if ((NULL == rowreq_ctx->data.moduleVersion) ||
        (sizeof(rowreq_ctx->data.moduleVersion) <
         (table_ptr->data.moduleVersion_len* sizeof(table_ptr->data.moduleVersion[0])))) {
        snmp_log(LOG_ERR,"not enough space for value (moduleVersion)\n");
        return MFD_ERROR;
    }
    rowreq_ctx->data.moduleVersion_len = table_ptr->data.moduleVersion_len* sizeof(table_ptr->data.moduleVersion[0]);
    memcpy( rowreq_ctx->data.moduleVersion, table_ptr->data.moduleVersion, table_ptr->data.moduleVersion_len* sizeof(table_ptr->data.moduleVersion[0]) );
    
    /*
     * setup/save data for moduleType
     * moduleType(6)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
     */
    /** no mapping */
    rowreq_ctx->data.moduleType = table_ptr->data.moduleType;
    
        
    /*
        * insert into table container
        */
    CONTAINER_INSERT(container, rowreq_ctx);
    ++count;
    }

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/

    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    DEBUGMSGT(("verbose:globalModuleTable:globalModuleTable_container_load",
               "inserted %" NETSNMP_PRIz "u records\n", count));

    return MFD_SUCCESS;
} /* globalModuleTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
globalModuleTable_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:globalModuleTable:globalModuleTable_container_free","called\n"));

    /*
     * TODO:380:M: Free globalModuleTable container data.
     */
} /* globalModuleTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
globalModuleTable_row_prep( globalModuleTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:globalModuleTable:globalModuleTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* globalModuleTable_row_prep */

/** @} */
