/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for trPatternTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "trPatternTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "trPatternTable_interface.h"

const oid trPatternTable_oid[] = { TRPATTERNTABLE_OID };
const int trPatternTable_oid_size = OID_LENGTH(trPatternTable_oid);

    trPatternTable_registration  trPatternTable_user_context;

void initialize_table_trPatternTable(void);
void shutdown_table_trPatternTable(void);


/**
 * Initializes the trPatternTable module
 */
void
init_trPatternTable(void)
{
    DEBUGMSGTL(("verbose:trPatternTable:init_trPatternTable","called\n"));

    /*
     * TODO:300:o: Perform trPatternTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("trPatternTable"))
        initialize_table_trPatternTable();

} /* init_trPatternTable */

/**
 * Shut-down the trPatternTable module (agent is exiting)
 */
void
shutdown_trPatternTable(void)
{
    if (should_init("trPatternTable"))
        shutdown_table_trPatternTable();

}

/**
 * Initialize the table trPatternTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_trPatternTable(void)
{
    trPatternTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:trPatternTable:initialize_table_trPatternTable","called\n"));

    /*
     * TODO:301:o: Perform trPatternTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize trPatternTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("trPatternTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _trPatternTable_initialize_interface(user_context, flags);
} /* initialize_table_trPatternTable */

/**
 * Shutdown the table trPatternTable 
 */
void
shutdown_table_trPatternTable(void)
{
    /*
     * call interface shutdown code
     */
    _trPatternTable_shutdown_interface(&trPatternTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
trPatternTable_rowreq_ctx_init(trPatternTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:trPatternTable:trPatternTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra trPatternTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* trPatternTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void trPatternTable_rowreq_ctx_cleanup(trPatternTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:trPatternTable:trPatternTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra trPatternTable rowreq cleanup.
     */
} /* trPatternTable_rowreq_ctx_cleanup */

/************************************************************
 * the *_should_save routine is called to determine if a row
 * should be stored persistently.
 *
 * Note that this is not a 'dirty' check (i.e. if a row has changed),
 * but a check for volatile rows that should not be saved between
 * restarts.
 *
 * return 1 if the row should be stored
 * return 0 if the row should not be stored
 */
int
trPatternTable_container_should_save(trPatternTable_rowreq_ctx * rowreq_ctx)
{
    
    return 1; /* save the row */
}

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
trPatternTable_pre_request(trPatternTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:trPatternTable:trPatternTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform trPatternTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* trPatternTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
trPatternTable_post_request(trPatternTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:trPatternTable:trPatternTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform trPatternTable post-request actions.
     */

    /*
     * check to set if any rows were changed.
     */
    if (trPatternTable_dirty_get()) {
        /*
         * check if request was successful. If so, this would be
         * a good place to save data to its persistent store.
         */
        if (MFD_SUCCESS == rc) {
            /*
             * save changed rows, if you haven't already
             */
            snmp_store(netsnmp_ds_get_string(NETSNMP_DS_LIBRARY_ID,
                                             NETSNMP_DS_LIB_APPTYPE));
        }
        
        trPatternTable_dirty_set(0); /* clear table dirty flag */
    }

    return MFD_SUCCESS;
} /* trPatternTable_post_request */


/** @{ */
