/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef CABINETENVIRONDEVICESTABLE_DATA_ACCESS_H
#define CABINETENVIRONDEVICESTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cabinetEnvironDevicesTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::cabinetEnvironDevicesTable is subid 2 of cabinetEnvironment.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.12.2, length: 12
*/


    int cabinetEnvironDevicesTable_init_data(cabinetEnvironDevicesTable_registration * cabinetEnvironDevicesTable_reg);


    /*
     * TODO:180:o: Review cabinetEnvironDevicesTable cache timeout.
     * The number of seconds before the cache times out
     */
#define CABINETENVIRONDEVICESTABLE_CACHE_TIMEOUT   1

void cabinetEnvironDevicesTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void cabinetEnvironDevicesTable_container_shutdown(netsnmp_container *container_ptr);

int cabinetEnvironDevicesTable_container_load(netsnmp_container *container);
void cabinetEnvironDevicesTable_container_free(netsnmp_container *container);

int cabinetEnvironDevicesTable_cache_load(netsnmp_container *container);
void cabinetEnvironDevicesTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int cabinetEnvironDevicesTable_row_prep( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx);

int cabinetEnvironDevicesTable_validate_index( cabinetEnvironDevicesTable_registration * cabinetEnvironDevicesTable_reg,
                               cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx);
int cabinetEnvironDeviceNumber_check_index( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx ); /* internal */
int cabinetEnvironDeviceIndex_check_index( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx ); /* internal */


#ifdef __cplusplus
}
#endif

#endif /* CABINETENVIRONDEVICESTABLE_DATA_ACCESS_H */
