/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-set.m2c
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "cabinetEnvironDevicesTable.h"


/** @defgroup data_set data_set: Routines to set data
 *
 * These routines are used to set the value for individual objects. The
 * row context is passed, along with the new value.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cabinetEnvironDevicesTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::cabinetEnvironDevicesTable is subid 2 of cabinetEnvironment.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.12.2, length: 12
*/
    /*
     * NOTE: if you update this chart, please update the versions in
     *       local/mib2c-conf.d/parent-set.m2i
     *       agent/mibgroup/helpers/baby_steps.c
     * while you're at it.
     */
    /*
     ***********************************************************************
     * Baby Steps Flow Chart (2004.06.05)                                  *
     *                                                                     *
     * +--------------+    +================+    U = unconditional path    *
     * |optional state|    ||required state||    S = path for success      *
     * +--------------+    +================+    E = path for error        *
     ***********************************************************************
     *
     *                        +--------------+
     *                        |     pre      |
     *                        |   request    |
     *                        +--------------+
     *                               | U
     *                        +==============+
     *       +----------------||  object    ||
     *       |              E ||  lookup    ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |              E ||   check    ||
     *       |<---------------||   values   ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |       +<-------||   undo     ||
     *       |       |      E ||   setup    ||
     *       |       |        +==============+
     *       |       |               | S
     *       |       |        +==============+
     *       |       |        ||    set     ||-------------------------->+
     *       |       |        ||   value    || E                         |
     *       |       |        +==============+                           |
     *       |       |               | S                                 |
     *       |       |        +--------------+                           |
     *       |       |        |    check     |-------------------------->|
     *       |       |        |  consistency | E                         |
     *       |       |        +--------------+                           |
     *       |       |               | S                                 |
     *       |       |        +==============+         +==============+  |
     *       |       |        ||   commit   ||-------->||     undo   ||  |
     *       |       |        ||            || E       ||    commit  ||  |
     *       |       |        +==============+         +==============+  |
     *       |       |               | S                     U |<--------+
     *       |       |        +--------------+         +==============+
     *       |       |        | irreversible |         ||    undo    ||
     *       |       |        |    commit    |         ||     set    ||
     *       |       |        +--------------+         +==============+
     *       |       |               | U                     U |
     *       |       +-------------->|<------------------------+
     *       |                +==============+
     *       |                ||   undo     ||
     *       |                ||  cleanup   ||
     *       |                +==============+
     *       +---------------------->| U
     *                        +--------------+
     *                        |    post      |
     *                        |   request    |
     *                        +--------------+
     *
     */

/**
 * Setup up context with information needed to undo a set request.
 *
 * This function will be called before the individual node undo setup
 * functions are called. If you need to do any undo setup that is not
 * related to a specific column, you can do it here.
 *
 * Note that the undo context has been allocated with
 * cabinetEnvironDevicesTable_allocate_data(), but may need extra
 * initialization similar to what you may have done in
 * cabinetEnvironDevicesTable_rowreq_ctx_init().
 * Note that an individual node's undo_setup function will only be called
 * if that node is being set to a new value.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in the node's undo_setup
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (cabinetEnvironDevicesTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
cabinetEnvironDevicesTable_undo_setup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDevicesTable_undo_setup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> Setup cabinetEnvironDevicesTable undo.
     * set up cabinetEnvironDevicesTable undo information, in preparation for a set.
     * Undo storage is in (* cabinetEnvironDeviceErrorStatus_val_ptr )*
     */

    return rc;
} /* cabinetEnvironDevicesTable_undo_setup */

/**
 * Undo a set request.
 *
 * This function will be called before the individual node undo
 * functions are called. If you need to do any undo that is not
 * related to a specific column, you can do it here.
 *
 * Note that an individual node's undo function will only be called
 * if that node is being set to a new value.
 *
 * If there is anything  specific to a particular column (e.g. releasing
 * memory for a string), you should do that setup in the node's undo
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (cabinetEnvironDevicesTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
cabinetEnvironDevicesTable_undo( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDevicesTable_undo","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:451:M: |-> cabinetEnvironDevicesTable undo.
     * cabinetEnvironDevicesTable undo information, in response to a failed set.
     * Undo storage is in (* cabinetEnvironDeviceErrorStatus_val_ptr )*
     */

    return rc;
} /* cabinetEnvironDevicesTable_undo_setup */

/**
 * Cleanup up context undo information.
 *
 * This function will be called after set/commit processing. If you
 * allocated any resources in undo_setup, this is the place to release
 * those resources.
 *
 * This function is called regardless of the success or failure of the set
 * request. If you need to perform different steps for cleanup depending
 * on success or failure, you can add a flag to the rowreq_ctx.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (cabinetEnvironDevicesTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
cabinetEnvironDevicesTable_undo_cleanup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDevicesTable_undo_cleanup","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:452:M: |-> Cleanup cabinetEnvironDevicesTable undo.
     * Undo storage is in (* cabinetEnvironDeviceErrorStatus_val_ptr )*
     */

    return rc;
} /* cabinetEnvironDevicesTable_undo_cleanup */

/**
 * commit new values.
 *
 * At this point, you should have done everything you can to ensure that
 * this commit will not fail.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * cabinetEnvironDevicesTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param cabinetEnvironDevicesTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
cabinetEnvironDevicesTable_commit( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    int             save_flags;

    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDevicesTable_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * save flags, then clear until we actually do something
     */
    save_flags = rowreq_ctx->column_set_flags;
    rowreq_ctx->column_set_flags = 0;

    /*
     * commit cabinetEnvironDevicesTable data
     * 1) check the column's flag in save_flags to see if it was set.
     * 2) clear the flag when you handle that column
     * 3) set the column's flag in column_set_flags if it needs undo
     *    processing in case of a failure.
     */
    if (save_flags & COLUMN_CABINETENVIRONDEVICETYPE_FLAG) {
       save_flags &= ~COLUMN_CABINETENVIRONDEVICETYPE_FLAG; /* clear cabinetEnvironDeviceType */
       /*
        * TODO:482:o: |-> commit column cabinetEnvironDeviceType.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"cabinetEnvironDevicesTable column cabinetEnvironDeviceType commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo cabinetEnvironDeviceType
             */
            rowreq_ctx->column_set_flags |= COLUMN_CABINETENVIRONDEVICETYPE_FLAG;
       }
    }

    if (save_flags & COLUMN_CABINETENVIRONDEVICEDESCRIPTION_FLAG) {
       save_flags &= ~COLUMN_CABINETENVIRONDEVICEDESCRIPTION_FLAG; /* clear cabinetEnvironDeviceDescription */
       /*
        * TODO:482:o: |-> commit column cabinetEnvironDeviceDescription.
        */
       rc = -1;
       if(-1 == rc) {
           snmp_log(LOG_ERR,"cabinetEnvironDevicesTable column cabinetEnvironDeviceDescription commit failed\n");
       }
       else {
            /*
             * set flag, in case we need to undo cabinetEnvironDeviceDescription
             */
            rowreq_ctx->column_set_flags |= COLUMN_CABINETENVIRONDEVICEDESCRIPTION_FLAG;
       }
    }

    /*
     * if we successfully commited this row, set the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags |= MFD_ROW_DIRTY;
    }

    if (save_flags) {
       snmp_log(LOG_ERR, "unhandled columns (0x%x) in commit\n", save_flags);
       return MFD_ERROR;
    }

    return rc;
} /* cabinetEnvironDevicesTable_commit */

/**
 * undo commit new values.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * cabinetEnvironDevicesTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param cabinetEnvironDevicesTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
cabinetEnvironDevicesTable_undo_commit( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDevicesTable_undo_commit","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:485:M: |-> Undo cabinetEnvironDevicesTable commit.
     * check each column's flag in rowreq_ctx->column_set_flags to see
     * if it was set during commit, then undo it.
     *
     * eg: if (rowreq_ctx->column_set_flags & COLUMN_CABINETENVIRONDEVICETYPE_FLAG) {}
     * eg: if (rowreq_ctx->column_set_flags & COLUMN_CABINETENVIRONDEVICEDESCRIPTION_FLAG) {}
     */

    
    /*
     * if we successfully un-commited this row, clear the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return rc;
} /* cabinetEnvironDevicesTable_undo_commit */

/*
 * TODO:440:M: Implement cabinetEnvironDevicesTable node value checks.
 * TODO:450:M: Implement cabinetEnvironDevicesTable undo functions.
 * TODO:460:M: Implement cabinetEnvironDevicesTable set functions.
 * TODO:480:M: Implement cabinetEnvironDevicesTable commit functions.
 */
/*---------------------------------------------------------------------
 * NTCIP1202-v03::cabinetEnvironDeviceEntry.cabinetEnvironDeviceType
 * cabinetEnvironDeviceType is subid 2 of cabinetEnvironDeviceEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1206.4.2.1.12.2.1.2
 * Description:
<Definition> The type of environment monitoring device to
monitor the cabinet is an enumerated integer.
other: the type of environmental monitoring device is not defined
by this standard.
door: this cabinet environmental monitoring device is a door to
the cabinet.
fan: this cabinet environmental monitoring device is a fan within
the cabinet.
heater: this cabinet environmental monitoring device is a heater
within the cabinet.
floatSwitch: this cabinet environmental monitoring device is a
float switch for water level detection.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.12.2.1.2
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 5. Values:  other(1), door(2), fan(3), heater(4), floatSwitch(5)
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cabinetEnvironDeviceType_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * cabinetEnvironDevicesTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  other(1), door(2), fan(3), heater(4), floatSwitch(5)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
cabinetEnvironDeviceType_check_value( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, u_long cabinetEnvironDeviceType_val)
{
    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDeviceType_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid cabinetEnvironDeviceType value.
     */

    return MFD_SUCCESS; /* cabinetEnvironDeviceType value not illegal */
} /* cabinetEnvironDeviceType_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (cabinetEnvironDevicesTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * cabinetEnvironDevicesTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
cabinetEnvironDeviceType_undo_setup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDeviceType_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup cabinetEnvironDeviceType undo.
     */
    /*
     * copy cabinetEnvironDeviceType data
     * set rowreq_ctx->undo->cabinetEnvironDeviceType from rowreq_ctx->data.cabinetEnvironDeviceType
     */
    rowreq_ctx->undo->cabinetEnvironDeviceType = rowreq_ctx->data.cabinetEnvironDeviceType;


    return MFD_SUCCESS;
} /* cabinetEnvironDeviceType_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param cabinetEnvironDeviceType_val
 *        A long containing the new value.
 */
int
cabinetEnvironDeviceType_set( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, u_long cabinetEnvironDeviceType_val )
{

    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDeviceType_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set cabinetEnvironDeviceType value.
     * set cabinetEnvironDeviceType value in rowreq_ctx->data
     */
    rowreq_ctx->data.cabinetEnvironDeviceType = cabinetEnvironDeviceType_val;

    return MFD_SUCCESS;
} /* cabinetEnvironDeviceType_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
cabinetEnvironDeviceType_undo( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDeviceType_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up cabinetEnvironDeviceType undo.
     */
    /*
     * copy cabinetEnvironDeviceType data
     * set rowreq_ctx->data.cabinetEnvironDeviceType from rowreq_ctx->undo->cabinetEnvironDeviceType
     */
    rowreq_ctx->data.cabinetEnvironDeviceType = rowreq_ctx->undo->cabinetEnvironDeviceType;

    
    return MFD_SUCCESS;
} /* cabinetEnvironDeviceType_undo */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::cabinetEnvironDeviceEntry.cabinetEnvironDeviceDescription
 * cabinetEnvironDeviceDescription is subid 4 of cabinetEnvironDeviceEntry.
 * Its status is Mandatory, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.1206.4.2.1.12.2.1.4
 * Description:
<Definition> Human-readable description of the cabinet
environmental device. This value should provide enough
information for maintenance personnel to identify the type (door,
fan, heater, etc.) and physical location of the device defined in
this row within the CU or CU cabinet.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.12.2.1.4
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   1
 *
 * Ranges:  0 - 64;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 64)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param cabinetEnvironDeviceDescription_val_ptr
 *        A char containing the new value.
 * @param cabinetEnvironDeviceDescription_val_ptr_len
 *        The size (in bytes) of the data pointed to by cabinetEnvironDeviceDescription_val_ptr
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * cabinetEnvironDevicesTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_OCTET_STR
 *    The length is < sizeof(rowreq_ctx->data.cabinetEnvironDeviceDescription).
 *    The length is in (one of) the range set(s):  0 - 64
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
cabinetEnvironDeviceDescription_check_value( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, char *cabinetEnvironDeviceDescription_val_ptr,  size_t cabinetEnvironDeviceDescription_val_ptr_len)
{
    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDeviceDescription_check_value","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != cabinetEnvironDeviceDescription_val_ptr);

    /*
     * TODO:441:o: |-> Check for valid cabinetEnvironDeviceDescription value.
     */

    return MFD_SUCCESS; /* cabinetEnvironDeviceDescription value not illegal */
} /* cabinetEnvironDeviceDescription_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (cabinetEnvironDevicesTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * cabinetEnvironDevicesTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
cabinetEnvironDeviceDescription_undo_setup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDeviceDescription_undo_setup","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup cabinetEnvironDeviceDescription undo.
     */
    /*
     * copy cabinetEnvironDeviceDescription and cabinetEnvironDeviceDescription_len data
     * set rowreq_ctx->undo->cabinetEnvironDeviceDescription from rowreq_ctx->data.cabinetEnvironDeviceDescription
     */
    memcpy( rowreq_ctx->undo->cabinetEnvironDeviceDescription, rowreq_ctx->data.cabinetEnvironDeviceDescription,
            (rowreq_ctx->data.cabinetEnvironDeviceDescription_len * sizeof(rowreq_ctx->undo->cabinetEnvironDeviceDescription[0])));
    rowreq_ctx->undo->cabinetEnvironDeviceDescription_len = rowreq_ctx->data.cabinetEnvironDeviceDescription_len;


    return MFD_SUCCESS;
} /* cabinetEnvironDeviceDescription_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param cabinetEnvironDeviceDescription_val_ptr
 *        A char containing the new value.
 * @param cabinetEnvironDeviceDescription_val_ptr_len
 *        The size (in bytes) of the data pointed to by cabinetEnvironDeviceDescription_val_ptr
 */
int
cabinetEnvironDeviceDescription_set( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, char *cabinetEnvironDeviceDescription_val_ptr,  size_t cabinetEnvironDeviceDescription_val_ptr_len )
{

    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDeviceDescription_set","called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != cabinetEnvironDeviceDescription_val_ptr);

    /*
     * TODO:461:M: |-> Set cabinetEnvironDeviceDescription value.
     * set cabinetEnvironDeviceDescription value in rowreq_ctx->data
     */
    memcpy( rowreq_ctx->data.cabinetEnvironDeviceDescription, cabinetEnvironDeviceDescription_val_ptr, cabinetEnvironDeviceDescription_val_ptr_len );
    /** convert bytes to number of char */
    rowreq_ctx->data.cabinetEnvironDeviceDescription_len = cabinetEnvironDeviceDescription_val_ptr_len / sizeof(cabinetEnvironDeviceDescription_val_ptr[0]);

    return MFD_SUCCESS;
} /* cabinetEnvironDeviceDescription_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
cabinetEnvironDeviceDescription_undo( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{

    DEBUGMSGTL(("verbose:cabinetEnvironDevicesTable:cabinetEnvironDeviceDescription_undo","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up cabinetEnvironDeviceDescription undo.
     */
    /*
     * copy cabinetEnvironDeviceDescription and cabinetEnvironDeviceDescription_len data
     * set rowreq_ctx->data.cabinetEnvironDeviceDescription from rowreq_ctx->undo->cabinetEnvironDeviceDescription
     */
    memcpy( rowreq_ctx->data.cabinetEnvironDeviceDescription, rowreq_ctx->undo->cabinetEnvironDeviceDescription,
            (rowreq_ctx->undo->cabinetEnvironDeviceDescription_len * sizeof(rowreq_ctx->data.cabinetEnvironDeviceDescription[0])));
    rowreq_ctx->data.cabinetEnvironDeviceDescription_len = rowreq_ctx->undo->cabinetEnvironDeviceDescription_len;

    
    return MFD_SUCCESS;
} /* cabinetEnvironDeviceDescription_undo */

/**
 * check dependencies
 *
 * This is useful for for tables which have dependencies between columns
 * (or rows, or tables). For example, two columns allocating a percentage
 * of something add up 100%.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * cabinetEnvironDevicesTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @retval MFD_SUCCESS all the changes to the row are legal
 * @retval MFD_ERROR   one or more changes are not legal
 *
 * (see README-table-cabinetEnvironDevicesTable if you don't have dependencies)
 */
int
cabinetEnvironDevicesTable_check_dependencies(cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;
    
    DEBUGMSGTL(("internal:cabinetEnvironDevicesTable:cabinetEnvironDevicesTable_check_dependencies","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:470:o: Check cabinetEnvironDevicesTable row dependencies.
     * check that all new value are legal and consistent with each other
     */
    return rc;
} /* cabinetEnvironDevicesTable_check_dependencies */

/** @} */
