/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-set.m2c
 */
#ifndef CABINETENVIRONDEVICESTABLE_DATA_SET_H
#define CABINETENVIRONDEVICESTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table cabinetEnvironDevicesTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::cabinetEnvironDevicesTable is subid 2 of cabinetEnvironment.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.12.2, length: 12
*/


int cabinetEnvironDevicesTable_undo_setup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx);
int cabinetEnvironDevicesTable_undo_cleanup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx);
int cabinetEnvironDevicesTable_undo( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx);
int cabinetEnvironDevicesTable_commit( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx);
int cabinetEnvironDevicesTable_undo_commit( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx);


int cabinetEnvironDeviceType_check_value( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, u_long cabinetEnvironDeviceType_val);
int cabinetEnvironDeviceType_undo_setup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx );
int cabinetEnvironDeviceType_set( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, u_long cabinetEnvironDeviceType_val );
int cabinetEnvironDeviceType_undo( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx );

int cabinetEnvironDeviceDescription_check_value( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, char *cabinetEnvironDeviceDescription_val_ptr,  size_t cabinetEnvironDeviceDescription_val_ptr_len);
int cabinetEnvironDeviceDescription_undo_setup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx );
int cabinetEnvironDeviceDescription_set( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, char *cabinetEnvironDeviceDescription_val_ptr,  size_t cabinetEnvironDeviceDescription_val_ptr_len );
int cabinetEnvironDeviceDescription_undo( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx );

int cabinetEnvironDeviceOnStatus_check_value( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, u_long cabinetEnvironDeviceOnStatus_val);
int cabinetEnvironDeviceOnStatus_undo_setup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx );
int cabinetEnvironDeviceOnStatus_set( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, u_long cabinetEnvironDeviceOnStatus_val );
int cabinetEnvironDeviceOnStatus_undo( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx );

int cabinetEnvironDeviceErrorStatus_check_value( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, u_long cabinetEnvironDeviceErrorStatus_val);
int cabinetEnvironDeviceErrorStatus_undo_setup( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx );
int cabinetEnvironDeviceErrorStatus_set( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx, u_long cabinetEnvironDeviceErrorStatus_val );
int cabinetEnvironDeviceErrorStatus_undo( cabinetEnvironDevicesTable_rowreq_ctx *rowreq_ctx );


int cabinetEnvironDevicesTable_check_dependencies(cabinetEnvironDevicesTable_rowreq_ctx *ctx);


#ifdef __cplusplus
}
#endif

#endif /* CABINETENVIRONDEVICESTABLE_DATA_SET_H */
