/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef CHANNELERRORFLAGSTABLE_INTERFACE_H
#define CHANNELERRORFLAGSTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "channelErrorFlagsTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _channelErrorFlagsTable_initialize_interface(channelErrorFlagsTable_registration * user_ctx,
                                    u_long flags);
void _channelErrorFlagsTable_shutdown_interface(channelErrorFlagsTable_registration * user_ctx);

channelErrorFlagsTable_registration *
channelErrorFlagsTable_registration_get( void );

channelErrorFlagsTable_registration *
channelErrorFlagsTable_registration_set( channelErrorFlagsTable_registration * newreg );

netsnmp_container *channelErrorFlagsTable_container_get( void );
int channelErrorFlagsTable_container_size( void );

    channelErrorFlagsTable_rowreq_ctx * channelErrorFlagsTable_allocate_rowreq_ctx(void *);
void channelErrorFlagsTable_release_rowreq_ctx(channelErrorFlagsTable_rowreq_ctx *rowreq_ctx);

int channelErrorFlagsTable_index_to_oid(netsnmp_index *oid_idx,
                            channelErrorFlagsTable_mib_index *mib_idx);
int channelErrorFlagsTable_index_from_oid(netsnmp_index *oid_idx,
                              channelErrorFlagsTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void channelErrorFlagsTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* CHANNELERRORFLAGSTABLE_INTERFACE_H */
/** @} */
