/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef CHANNELERRORFLAGSTABLE_OIDS_H
#define CHANNELERRORFLAGSTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table channelErrorFlagsTable */
#define CHANNELERRORFLAGSTABLE_OID              1,3,6,1,4,1,59873,4,2,1,2,4


#define COLUMN_ERRORGROUPNUMBER         1
    
#define COLUMN_REDLAMPALLFAILURE         2
    
#define COLUMN_GREENLAMPALLFAILURE         3
    
#define COLUMN_YELLOWLAMPALLFAILURE         4
    
#define COLUMN_UNDESIREDREDSIGNAL         5
    
#define COLUMN_UNDESIREDGREENSIGNAL         6
    
#define COLUMN_UNDESIREDYELLOWSIGNAL         7
    

#define CHANNELERRORFLAGSTABLE_MIN_COL   COLUMN_ERRORGROUPNUMBER
#define CHANNELERRORFLAGSTABLE_MAX_COL   COLUMN_UNDESIREDYELLOWSIGNAL
    


#ifdef __cplusplus
}
#endif

#endif /* CHANNELERRORFLAGSTABLE_OIDS_H */
