/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for channelErrorFlagsTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "channelErrorFlagsTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "channelErrorFlagsTable_interface.h"

const oid channelErrorFlagsTable_oid[] = { CHANNELERRORFLAGSTABLE_OID };
const int channelErrorFlagsTable_oid_size = OID_LENGTH(channelErrorFlagsTable_oid);

    channelErrorFlagsTable_registration  channelErrorFlagsTable_user_context;

void initialize_table_channelErrorFlagsTable(void);
void shutdown_table_channelErrorFlagsTable(void);


/**
 * Initializes the channelErrorFlagsTable module
 */
void
init_channelErrorFlagsTable(void)
{
    DEBUGMSGTL(("verbose:channelErrorFlagsTable:init_channelErrorFlagsTable","called\n"));

    /*
     * TODO:300:o: Perform channelErrorFlagsTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("channelErrorFlagsTable"))
        initialize_table_channelErrorFlagsTable();

} /* init_channelErrorFlagsTable */

/**
 * Shut-down the channelErrorFlagsTable module (agent is exiting)
 */
void
shutdown_channelErrorFlagsTable(void)
{
    if (should_init("channelErrorFlagsTable"))
        shutdown_table_channelErrorFlagsTable();

}

/**
 * Initialize the table channelErrorFlagsTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_channelErrorFlagsTable(void)
{
    channelErrorFlagsTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:channelErrorFlagsTable:initialize_table_channelErrorFlagsTable","called\n"));

    /*
     * TODO:301:o: Perform channelErrorFlagsTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize channelErrorFlagsTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("channelErrorFlagsTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _channelErrorFlagsTable_initialize_interface(user_context, flags);
} /* initialize_table_channelErrorFlagsTable */

/**
 * Shutdown the table channelErrorFlagsTable 
 */
void
shutdown_table_channelErrorFlagsTable(void)
{
    /*
     * call interface shutdown code
     */
    _channelErrorFlagsTable_shutdown_interface(&channelErrorFlagsTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
channelErrorFlagsTable_rowreq_ctx_init(channelErrorFlagsTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:channelErrorFlagsTable:channelErrorFlagsTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra channelErrorFlagsTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* channelErrorFlagsTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void channelErrorFlagsTable_rowreq_ctx_cleanup(channelErrorFlagsTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:channelErrorFlagsTable:channelErrorFlagsTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra channelErrorFlagsTable rowreq cleanup.
     */
} /* channelErrorFlagsTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
channelErrorFlagsTable_pre_request(channelErrorFlagsTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:channelErrorFlagsTable:channelErrorFlagsTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform channelErrorFlagsTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* channelErrorFlagsTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
channelErrorFlagsTable_post_request(channelErrorFlagsTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:channelErrorFlagsTable:channelErrorFlagsTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform channelErrorFlagsTable post-request actions.
     */

    return MFD_SUCCESS;
} /* channelErrorFlagsTable_post_request */


/** @{ */
