/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef GLOBALCONFIGURATION_H
#define GLOBALCONFIGURATION_H

/* function declarations */
void init_globalConfiguration(void);
Netsnmp_Node_Handler handle_globalSetIDParameter;
Netsnmp_Node_Handler handle_globalMaxModules;
Netsnmp_Node_Handler handle_controllerBaseStandards;

#endif /* GLOBALCONFIGURATION_H */
