/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef CHANNELSTATUSGROUPTABLE_OIDS_H
#define CHANNELSTATUSGROUPTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table channelStatusGroupTable */
#define CHANNELSTATUSGROUPTABLE_OID              1,3,6,1,4,1,1206,4,2,1,8,4


#define COLUMN_CHANNELSTATUSGROUPNUMBER         1
    
#define COLUMN_CHANNELSTATUSGROUPREDS         2
    
#define COLUMN_CHANNELSTATUSGROUPYELLOWS         3
    
#define COLUMN_CHANNELSTATUSGROUPGREENS         4
    

#define CHANNELSTATUSGROUPTABLE_MIN_COL   COLUMN_CHANNELSTATUSGROUPNUMBER
#define CHANNELSTATUSGROUPTABLE_MAX_COL   COLUMN_CHANNELSTATUSGROUPGREENS
    


#ifdef __cplusplus
}
#endif

#endif /* CHANNELSTATUSGROUPTABLE_OIDS_H */
