/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file channelStatusGroupTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef CHANNELSTATUSGROUPTABLE_DATA_GET_H
#define CHANNELSTATUSGROUPTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table channelStatusGroupTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::channelStatusGroupTable is subid 4 of channel.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.8.4, length: 12
*/
    /*
     * indexes
     */

    int channelStatusGroupReds_get( channelStatusGroupTable_rowreq_ctx *rowreq_ctx, long * channelStatusGroupReds_val_ptr );
    int channelStatusGroupYellows_get( channelStatusGroupTable_rowreq_ctx *rowreq_ctx, long * channelStatusGroupYellows_val_ptr );
    int channelStatusGroupGreens_get( channelStatusGroupTable_rowreq_ctx *rowreq_ctx, long * channelStatusGroupGreens_val_ptr );


int channelStatusGroupTable_indexes_set_tbl_idx(channelStatusGroupTable_mib_index *tbl_idx, long channelStatusGroupNumber_val);
int channelStatusGroupTable_indexes_set(channelStatusGroupTable_rowreq_ctx *rowreq_ctx, long channelStatusGroupNumber_val);




#ifdef __cplusplus
}
#endif

#endif /* CHANNELSTATUSGROUPTABLE_DATA_GET_H */
/** @} */
