/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef PHASE_H
#define PHASE_H

/* function declarations */
void init_phase(void);
Netsnmp_Node_Handler handle_maxPhases;
Netsnmp_Node_Handler handle_maxPhaseGroups;

#endif /* PHASE_H */
