/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef CHANNELGENERALFAULTSTATETABLE_OIDS_H
#define CHANNELGENERALFAULTSTATETABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table ChannelGeneralFaultStateTable */
#define CHANNELGENERALFAULTSTATETABLE_OID              1,3,6,1,4,1,59873,4,2,1,2,6


#define COLUMN_CHANNELFAULTSTATUSGROUPNUMBER         1
    
#define COLUMN_CHANNELFAULTS         2
    

#define CHANNELGENERALFAULTSTATETABLE_MIN_COL   COLUMN_CHANNELFAULTSTATUSGROUPNUMBER
#define CHANNELGENERALFAULTSTATETABLE_MAX_COL   COLUMN_CHANNELFAULTS
    


#ifdef __cplusplus
}
#endif

#endif /* CHANNELGENERALFAULTSTATETABLE_OIDS_H */
