/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "trafficLightFaultStatusTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement trafficLightFaultStatusTable get routines.
 * TODO:240:M: Implement trafficLightFaultStatusTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table trafficLightFaultStatusTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * ISBAV-MIB::trafficLightFaultStatusTable is subid 4 of channel.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.40019.4.2.1.2.4, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement trafficLightFaultStatusTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param trafficLightFaultStatusIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
trafficLightFaultStatusTable_indexes_set_tbl_idx(trafficLightFaultStatusTable_mib_index *tbl_idx, long trafficLightFaultStatusIndex_val)
{
    DEBUGMSGTL(("verbose:trafficLightFaultStatusTable:trafficLightFaultStatusTable_indexes_set_tbl_idx","called\n"));

    /* trafficLightFaultStatusIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->trafficLightFaultStatusIndex = trafficLightFaultStatusIndex_val;
    

    return MFD_SUCCESS;
} /* trafficLightFaultStatusTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
trafficLightFaultStatusTable_indexes_set(trafficLightFaultStatusTable_rowreq_ctx *rowreq_ctx, long trafficLightFaultStatusIndex_val)
{
    DEBUGMSGTL(("verbose:trafficLightFaultStatusTable:trafficLightFaultStatusTable_indexes_set","called\n"));

    if(MFD_SUCCESS != trafficLightFaultStatusTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , trafficLightFaultStatusIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != trafficLightFaultStatusTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* trafficLightFaultStatusTable_indexes_set */


/*---------------------------------------------------------------------
 * ISBAV-MIB::trafficLightFaultStatusEntry.trafficLightFaultChannelNumber
 * trafficLightFaultChannelNumber is subid 2 of trafficLightFaultStatusEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.40019.4.2.1.2.4.1.2
 * Description:
<Definition>  Kanal tablosundaki
channelNumber bilgisini icerir.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.1.2.1.1
<Unit>  
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  1 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the trafficLightFaultChannelNumber data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param trafficLightFaultChannelNumber_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
trafficLightFaultChannelNumber_get( trafficLightFaultStatusTable_rowreq_ctx *rowreq_ctx, long * trafficLightFaultChannelNumber_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != trafficLightFaultChannelNumber_val_ptr );


    DEBUGMSGTL(("verbose:trafficLightFaultStatusTable:trafficLightFaultChannelNumber_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the trafficLightFaultChannelNumber data.
 * copy (* trafficLightFaultChannelNumber_val_ptr ) from rowreq_ctx->data
 */
    (* trafficLightFaultChannelNumber_val_ptr ) = rowreq_ctx->data.trafficLightFaultChannelNumber;

    return MFD_SUCCESS;
} /* trafficLightFaultChannelNumber_get */

/*---------------------------------------------------------------------
 * ISBAV-MIB::trafficLightFaultStatusEntry.trafficLightFaultGreenStatus
 * trafficLightFaultGreenStatus is subid 3 of trafficLightFaultStatusEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.40019.4.2.1.2.4.1.3
 * Description:
<Definition>
		Bit 0: Ariza yok
		Bit 1: Lamba arizasi(Kritik olmayan)
Bit 2: Kritik lamba arizasi
		Bit 3: Tum lamba arizasi
		Bit 4: Cakisma var	
		Bit 5: Sinyal cikis anahtari kisa devre / sinyal grup
cikisi kisa devre
		Bit 6: Sinyal cikis anahtari acik devre / sinyal grup
cikisi acik devre
	Bit 7: Rez.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.1.2.1.1
<Unit>  
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the trafficLightFaultGreenStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param trafficLightFaultGreenStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
trafficLightFaultGreenStatus_get( trafficLightFaultStatusTable_rowreq_ctx *rowreq_ctx, long * trafficLightFaultGreenStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != trafficLightFaultGreenStatus_val_ptr );


    DEBUGMSGTL(("verbose:trafficLightFaultStatusTable:trafficLightFaultGreenStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the trafficLightFaultGreenStatus data.
 * copy (* trafficLightFaultGreenStatus_val_ptr ) from rowreq_ctx->data
 */
    (* trafficLightFaultGreenStatus_val_ptr ) = rowreq_ctx->data.trafficLightFaultGreenStatus;

    return MFD_SUCCESS;
} /* trafficLightFaultGreenStatus_get */

/*---------------------------------------------------------------------
 * ISBAV-MIB::trafficLightFaultStatusEntry.trafficLightFaultYellowStatus
 * trafficLightFaultYellowStatus is subid 4 of trafficLightFaultStatusEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.40019.4.2.1.2.4.1.4
 * Description:
<Definition>
1 Byte	
		Bit 0: Ariza yok
		Bit 1: Lamba arizasi(Kritik olmayan)
Bit 2: Kritik lamba arizasi
		Bit 3: Tum lamba arizasi
		Bit 4: Cakisma var	
		Bit 5: Sinyal cikis anahtari kisa devre / sinyal grup
cikisi kisa devre
		Bit 6: Sinyal cikis anahtari acik devre / sinyal grup
cikisi acik devre
		Bit 7: Rez.	

<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.1.2.1.1
<Unit>  
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the trafficLightFaultYellowStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param trafficLightFaultYellowStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
trafficLightFaultYellowStatus_get( trafficLightFaultStatusTable_rowreq_ctx *rowreq_ctx, long * trafficLightFaultYellowStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != trafficLightFaultYellowStatus_val_ptr );


    DEBUGMSGTL(("verbose:trafficLightFaultStatusTable:trafficLightFaultYellowStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the trafficLightFaultYellowStatus data.
 * copy (* trafficLightFaultYellowStatus_val_ptr ) from rowreq_ctx->data
 */
    (* trafficLightFaultYellowStatus_val_ptr ) = rowreq_ctx->data.trafficLightFaultYellowStatus;

    return MFD_SUCCESS;
} /* trafficLightFaultYellowStatus_get */

/*---------------------------------------------------------------------
 * ISBAV-MIB::trafficLightFaultStatusEntry.trafficLightFaultRedStatus
 * trafficLightFaultRedStatus is subid 5 of trafficLightFaultStatusEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.40019.4.2.1.2.4.1.5
 * Description:
<Definition>
1 Byte	
		Bit 0: Ariza yok
		Bit 1: Lamba arizasi(Kritik olmayan)
Bit 2: Kritik lamba arizasi
		Bit 3: Tum lamba arizasi
		Bit 4: Cakisma var	
		Bit 5: Sinyal cikis anahtari kisa devre / sinyal grup
cikisi kisa devre
		Bit 6: Sinyal cikis anahtari acik devre / sinyal grup
cikisi acik devre
		Bit 7: Rez.		

<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.1.2.1.1
<Unit>  
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the trafficLightFaultRedStatus data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param trafficLightFaultRedStatus_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
trafficLightFaultRedStatus_get( trafficLightFaultStatusTable_rowreq_ctx *rowreq_ctx, long * trafficLightFaultRedStatus_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != trafficLightFaultRedStatus_val_ptr );


    DEBUGMSGTL(("verbose:trafficLightFaultStatusTable:trafficLightFaultRedStatus_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the trafficLightFaultRedStatus data.
 * copy (* trafficLightFaultRedStatus_val_ptr ) from rowreq_ctx->data
 */
    (* trafficLightFaultRedStatus_val_ptr ) = rowreq_ctx->data.trafficLightFaultRedStatus;

    return MFD_SUCCESS;
} /* trafficLightFaultRedStatus_get */



/** @} */
