/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "utils.h"
#include "coord.h"
#include "trPatternTable.h"
#include "coord_data.h"

/** Initializes the coord module */
void
init_coord(void)
{
    const oid maxTrPattern_oid[] = { 1,3,6,1,4,1,59873,4,2,1,9,1 };
    const oid signalPlanUpgrade_oid[] = { 1,3,6,1,4,1,59873,4,2,1,9,3 };

    DEBUGMSGTL(("coord", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("maxTrPattern", handle_maxTrPattern,
                               maxTrPattern_oid, OID_LENGTH(maxTrPattern_oid),
                               HANDLER_CAN_RONLY
        ));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("signalPlanUpgrade", handle_signalPlanUpgrade,
                               signalPlanUpgrade_oid, OID_LENGTH(signalPlanUpgrade_oid),
                               HANDLER_CAN_RWRITE
        ));
}

int
handle_maxTrPattern(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     get_coord_maxtrpattern(),
                                     sizeof(MAX_TR_PATTERN_TYPE));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_maxTrPattern\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}


int
handle_signalPlanUpgrade(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     get_signalPlanUpgrade(),
                                     sizeof(int));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            /* XXX: perform the value change here */
            set_signalPlanUpgrade((void *)requests->requestvb->val.integer);
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */

            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_signalPlanUpgrade\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}
