/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef SIGNALSTATE_H
#define SIGNALSTATE_H

/* function declarations */
void init_signalState(void);
Netsnmp_Node_Handler handle_maxSignalState;
Netsnmp_Node_Handler handle_signalPlanLastChangeTime;

#endif /* SIGNALSTATE_H */
