/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "vehicleDetectorStatusGroupTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement vehicleDetectorStatusGroupTable get routines.
 * TODO:240:M: Implement vehicleDetectorStatusGroupTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table vehicleDetectorStatusGroupTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::vehicleDetectorStatusGroupTable is subid 4 of detector.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.4, length: 12
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement vehicleDetectorStatusGroupTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param vehicleDetectorStatusGroupNumber_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
vehicleDetectorStatusGroupTable_indexes_set_tbl_idx(vehicleDetectorStatusGroupTable_mib_index *tbl_idx, long vehicleDetectorStatusGroupNumber_val)
{
    DEBUGMSGTL(("verbose:vehicleDetectorStatusGroupTable:vehicleDetectorStatusGroupTable_indexes_set_tbl_idx","called\n"));

    /* vehicleDetectorStatusGroupNumber(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->vehicleDetectorStatusGroupNumber = vehicleDetectorStatusGroupNumber_val;
    

    return MFD_SUCCESS;
} /* vehicleDetectorStatusGroupTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
vehicleDetectorStatusGroupTable_indexes_set(vehicleDetectorStatusGroupTable_rowreq_ctx *rowreq_ctx, long vehicleDetectorStatusGroupNumber_val)
{
    DEBUGMSGTL(("verbose:vehicleDetectorStatusGroupTable:vehicleDetectorStatusGroupTable_indexes_set","called\n"));

    if(MFD_SUCCESS != vehicleDetectorStatusGroupTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , vehicleDetectorStatusGroupNumber_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != vehicleDetectorStatusGroupTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* vehicleDetectorStatusGroupTable_indexes_set */


/*---------------------------------------------------------------------
 * NTCIP1202-v03::vehicleDetectorStatusGroupEntry.vehicleDetectorStatusGroupActive
 * vehicleDetectorStatusGroupActive is subid 2 of vehicleDetectorStatusGroupEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.4.1.2
 * Description:
<Definition> This object shall return the detection STATUS
of each detector associated with the group. Each detector shall
be represented as ON (detect) or OFF (no-detect) by individual
bits in this object. If a detector is ON then the associated bit
shall be set (1). If a detector is OFF then the associated bit
shall be clear (0).
Bit 7: Det # = ( vehicleDetectorStatusGroupNumber * 8)
Bit 6: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 1
Bit 5: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 2
Bit 4: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 3
Bit 3: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 4
Bit 2: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 5
Bit 1: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 6
Bit 0: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 7
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.4.1.2
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the vehicleDetectorStatusGroupActive data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param vehicleDetectorStatusGroupActive_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
vehicleDetectorStatusGroupActive_get( vehicleDetectorStatusGroupTable_rowreq_ctx *rowreq_ctx, long * vehicleDetectorStatusGroupActive_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != vehicleDetectorStatusGroupActive_val_ptr );


    DEBUGMSGTL(("verbose:vehicleDetectorStatusGroupTable:vehicleDetectorStatusGroupActive_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the vehicleDetectorStatusGroupActive data.
 * copy (* vehicleDetectorStatusGroupActive_val_ptr ) from rowreq_ctx->data
 */
    (* vehicleDetectorStatusGroupActive_val_ptr ) = rowreq_ctx->data.vehicleDetectorStatusGroupActive;

    return MFD_SUCCESS;
} /* vehicleDetectorStatusGroupActive_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::vehicleDetectorStatusGroupEntry.vehicleDetectorStatusGroupAlarms
 * vehicleDetectorStatusGroupAlarms is subid 3 of vehicleDetectorStatusGroupEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.4.1.3
 * Description:
<Definition> This object shall return the alarm status of
the detectors associated with the group. Each detector alarm
status shall be represented as ON or OFF by individual bits in
this object. If any detector alarm (defined in the
vehicleDetectorAlarm object) is active the associated bit shall
be set (1). If a detector alarm is not active the associated bit
shall be clear (0).
Bit 7: Det # = ( vehicleDetectorStatusGroupNumber * 8)
Bit 6: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 1
Bit 5: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 2
Bit 4: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 3
Bit 3: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 4
Bit 2: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 5
Bit 1: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 6
Bit 0: Det # = ( vehicleDetectorStatusGroupNumber * 8) - 7
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.4.1.3
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the vehicleDetectorStatusGroupAlarms data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param vehicleDetectorStatusGroupAlarms_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
vehicleDetectorStatusGroupAlarms_get( vehicleDetectorStatusGroupTable_rowreq_ctx *rowreq_ctx, long * vehicleDetectorStatusGroupAlarms_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != vehicleDetectorStatusGroupAlarms_val_ptr );


    DEBUGMSGTL(("verbose:vehicleDetectorStatusGroupTable:vehicleDetectorStatusGroupAlarms_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the vehicleDetectorStatusGroupAlarms data.
 * copy (* vehicleDetectorStatusGroupAlarms_val_ptr ) from rowreq_ctx->data
 */
    (* vehicleDetectorStatusGroupAlarms_val_ptr ) = rowreq_ctx->data.vehicleDetectorStatusGroupAlarms;

    return MFD_SUCCESS;
} /* vehicleDetectorStatusGroupAlarms_get */



/** @} */
