/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "volumeOccupancyTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement volumeOccupancyTable get routines.
 * TODO:240:M: Implement volumeOccupancyTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table volumeOccupancyTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::volumeOccupancyTable is subid 4 of volumeOccupancyReport.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.5.4, length: 13
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement volumeOccupancyTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param vehicleDetectorNumber_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
volumeOccupancyTable_indexes_set_tbl_idx(volumeOccupancyTable_mib_index *tbl_idx, long vehicleDetectorNumber_val)
{
    DEBUGMSGTL(("verbose:volumeOccupancyTable:volumeOccupancyTable_indexes_set_tbl_idx","called\n"));

    /* vehicleDetectorNumber(1)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->vehicleDetectorNumber = vehicleDetectorNumber_val;
    

    return MFD_SUCCESS;
} /* volumeOccupancyTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
volumeOccupancyTable_indexes_set(volumeOccupancyTable_rowreq_ctx *rowreq_ctx, long vehicleDetectorNumber_val)
{
    DEBUGMSGTL(("verbose:volumeOccupancyTable:volumeOccupancyTable_indexes_set","called\n"));

    if(MFD_SUCCESS != volumeOccupancyTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , vehicleDetectorNumber_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != volumeOccupancyTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* volumeOccupancyTable_indexes_set */


/*---------------------------------------------------------------------
 * NTCIP1202-v03::volumeOccupancyEntry.detectorVolume
 * detectorVolume is subid 1 of volumeOccupancyEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.5.4.1.1
 * Description:
<Definition> Detector Volume data collected over the
volumeOccupancyPeriod. This value shall range from 0 to 254
indicating the volume of traffic crossing the associated
detectorNumber during the collection period. The value 255 shall
indicate volume overflow.
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.5.4.1.1
<Unit> volume
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the detectorVolume data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param detectorVolume_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
detectorVolume_get( volumeOccupancyTable_rowreq_ctx *rowreq_ctx, long * detectorVolume_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != detectorVolume_val_ptr );


    DEBUGMSGTL(("verbose:volumeOccupancyTable:detectorVolume_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the detectorVolume data.
 * copy (* detectorVolume_val_ptr ) from rowreq_ctx->data
 */
    (* detectorVolume_val_ptr ) = rowreq_ctx->data.detectorVolume;

    return MFD_SUCCESS;
} /* detectorVolume_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::volumeOccupancyEntry.detectorOccupancy
 * detectorOccupancy is subid 2 of volumeOccupancyEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.5.4.1.2
 * Description:
<Definition> Detector Occupancy as a percentage of the
volumeOccupancyPeriod over which the data was collected or
Detector Unit Diagnostic Information. The value of the object
shall indicate occupancy or detector diagnostic information as
follows:
Range  Meaning
0-200  Detector Occupancy in 0.5% Increments
201-209 Reserved
210  Max Presence Fault
211  No Activity Fault
212  Open loop Fault
213  Shorted loop Fault
214  Excessive Change Fault
215  Reserved
216  Watchdog Fault
217  Erratic Output Fault
218-255 Reserved

Faults shall be indicated for all collection periods during which
a fault is detected if either occupancy data or volume data is
being collected. The highest numbered fault shall be presented if
more than one fault is active (i.e. indicate OpenLoop rather than
NoActivity).
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.5.4.1.2
<Unit> occupancy
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the detectorOccupancy data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param detectorOccupancy_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
detectorOccupancy_get( volumeOccupancyTable_rowreq_ctx *rowreq_ctx, long * detectorOccupancy_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != detectorOccupancy_val_ptr );


    DEBUGMSGTL(("verbose:volumeOccupancyTable:detectorOccupancy_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the detectorOccupancy data.
 * copy (* detectorOccupancy_val_ptr ) from rowreq_ctx->data
 */
    (* detectorOccupancy_val_ptr ) = rowreq_ctx->data.detectorOccupancy;

    return MFD_SUCCESS;
} /* detectorOccupancy_get */

/*---------------------------------------------------------------------
 * NTCIP1202-v03::volumeOccupancyEntry.detectorAvgSpeed
 * detectorAvgSpeed is subid 3 of volumeOccupancyEntry.
 * Its status is Mandatory, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.5.4.1.3
 * Description:
<Definition>Average vehicle speed during the
volumeOccupancyPeriod over which the data was collected. The
value of the object shall indicate average vehicle speed as
follows:
Range Meaning
0-508 Average vehicle speed in 0.5 kilometers per hour
509 Reserved
510 Average vehicle speed is 255 kilometers per hour or higher
511 Invalid or missing value
<Object Identifier> 1.3.6.1.4.1.1206.4.2.1.2.5.4.1.3
<Unit>0.5 kilometers/hour
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 1
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *   defval: 511
 *
 * Ranges:  0 - 511;
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the detectorAvgSpeed data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param detectorAvgSpeed_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
detectorAvgSpeed_get( volumeOccupancyTable_rowreq_ctx *rowreq_ctx, long * detectorAvgSpeed_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != detectorAvgSpeed_val_ptr );


    DEBUGMSGTL(("verbose:volumeOccupancyTable:detectorAvgSpeed_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the detectorAvgSpeed data.
 * copy (* detectorAvgSpeed_val_ptr ) from rowreq_ctx->data
 */
    (* detectorAvgSpeed_val_ptr ) = rowreq_ctx->data.detectorAvgSpeed;

    return MFD_SUCCESS;
} /* detectorAvgSpeed_get */



/** @} */
