/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef VOLUMEOCCUPANCYTABLE_DATA_ACCESS_H
#define VOLUMEOCCUPANCYTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table volumeOccupancyTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * NTCIP1202-v03::volumeOccupancyTable is subid 4 of volumeOccupancyReport.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.1206.4.2.1.2.5.4, length: 13
*/


    int volumeOccupancyTable_init_data(volumeOccupancyTable_registration * volumeOccupancyTable_reg);


    /*
     * TODO:180:o: Review volumeOccupancyTable cache timeout.
     * The number of seconds before the cache times out
     */
#define VOLUMEOCCUPANCYTABLE_CACHE_TIMEOUT   1

void volumeOccupancyTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void volumeOccupancyTable_container_shutdown(netsnmp_container *container_ptr);

int volumeOccupancyTable_container_load(netsnmp_container *container);
void volumeOccupancyTable_container_free(netsnmp_container *container);

int volumeOccupancyTable_cache_load(netsnmp_container *container);
void volumeOccupancyTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int volumeOccupancyTable_row_prep( volumeOccupancyTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* VOLUMEOCCUPANCYTABLE_DATA_ACCESS_H */
