/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef VOLUMEOCCUPANCYTABLE_OIDS_H
#define VOLUMEOCCUPANCYTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table volumeOccupancyTable */
#define VOLUMEOCCUPANCYTABLE_OID              1,3,6,1,4,1,1206,4,2,1,2,5,4


#define COLUMN_DETECTORVOLUME         1
    
#define COLUMN_DETECTOROCCUPANCY         2
    
#define COLUMN_DETECTORAVGSPEED         3
    

#define VOLUMEOCCUPANCYTABLE_MIN_COL   COLUMN_DETECTORVOLUME
#define VOLUMEOCCUPANCYTABLE_MAX_COL   COLUMN_DETECTORAVGSPEED
    


#ifdef __cplusplus
}
#endif

#endif /* VOLUMEOCCUPANCYTABLE_OIDS_H */
