/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file userOperationsTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef USEROPERATIONSTABLE_DATA_GET_H
#define USEROPERATIONSTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table userOperationsTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * kgm-ortak::userOperationsTable is subid 2 of user.
 * Its status is Mandatory.
 * OID: .1.3.6.1.4.1.59873.4.2.1.5.2, length: 12
*/
    /*
     * indexes
     */

    int userOperationsType_get( userOperationsTable_rowreq_ctx *rowreq_ctx, u_long * userOperationsType_val_ptr );
    int userOperationsTime_get( userOperationsTable_rowreq_ctx *rowreq_ctx, u_long * userOperationsTime_val_ptr );
    int userOperationsULoginName_get( userOperationsTable_rowreq_ctx *rowreq_ctx, char **userOperationsULoginName_val_ptr_ptr, size_t *userOperationsULoginName_val_ptr_len_ptr );


int userOperationsTable_indexes_set_tbl_idx(userOperationsTable_mib_index *tbl_idx, long userOperationsIndex_val);
int userOperationsTable_indexes_set(userOperationsTable_rowreq_ctx *rowreq_ctx, long userOperationsIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* USEROPERATIONSTABLE_DATA_GET_H */
/** @} */
