/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef KGMDEDECTORMODULESTATUS_H
#define KGMDEDECTORMODULESTATUS_H

#define DEDECTOR_MODULE_DUMMY_VAL 0xFFFFFFFF

/* function declarations */
void init_kgmDedectorModuleStatus(void);
Netsnmp_Node_Handler handle_kgmDedectorModuleStatus;
Netsnmp_Node_Handler handle_otherModulesStatus;
void check_dedectorModule_traps();
#endif /* KGMDEDECTORMODULESTATUS_H */
